### ISSUE TITLE
How to select just Segresnet3D as the network

### ISSUE THREAD

**Issue by baoqiangmaUMCG** [Project-MONAI/tutorials#1007]
Hi,

I want to setting only use 'Segresnet3d' as the defualt model instead of all models. Do you know how to set it in the alogs below ?

 bundle_generator = BundleGen(
        algo_path=result_dir,
        algos=used_algorithms,
        data_stats_filename=datastats_file,
        data_src_cfg_name=input,
    )

**Comment by baoqiangmaUMCG** [comment]
This is a part of Auto3Dseg module code

**Comment by mingxin-zheng** [comment]
Hi @baoqiangmaUMCG , sorry this isn't supported until this [PR](https://github.com/Project-MONAI/MONAI/pull/5376) is approved. 

But it isn't impossible to achieve what you want. You need to install the monai in the edit mode with source code. Then find [bundle_gen.py](https://github.com/Project-MONAI/MONAI/blob/044295e31362da8fdbdaa14a84a1fb1969a69248/monai/apps/auto3dseg/bundle_gen.py#L285) and remove all the algorithms other than `segresnet`.

**Comment by wyli** [comment]
I think it's been fixed by https://github.com/Project-MONAI/MONAI/commit/aef2ecccd4b4d0a663fb8a256ee36d8b00bdde10

**Comment by myron** [comment]
If I understand your question, you can simply use:

AutoRunner(input=input_config, algos = 'segresnet')
#runner.set_num_fold(1)
runner.run()
