### ISSUE TITLE
How can I using another model?

### ISSUE THREAD

**Issue by SiYeon-Kwon** [Project-MONAI/tutorials#1018]
**Please use MONAI's Discussions tab**
For questions relating to MONAI usage, please do not create an issue.

Instead, use [MONAI's GitHub Discussions tab](https://github.com/Project-MONAI/MONAI/discussions). This can be found on the MONAI repository's main page (not the tutorials) next to Issues and Pull Requests along the top.

Hi, I interested in medical AI and Monai.

I want to running another model in classification tutorial, but just Densenet is running in tutorial.

I also know that tensor is problem, and channel and size are unmatched.

Already run RandomResizeCrop function in torch.nn for resize 64 size to 7, add layer with pretrained model.

only pretrained model is running in tutorial.....

So, how can I using another model in tutorial?

plz let me know ㅠㅠㅠㅠㅠㅠ

**Comment by KumoLiu** [comment]
Hi @SiYeon-Kwon, you can find more models in the `networks/nets` fold, here is the link https://github.com/Project-MONAI/MONAI/tree/dev/monai/networks/nets.
Hope it can help you, thanks!

**Comment by SiYeon-Kwon** [comment]
> Hi @SiYeon-Kwon, you can find more models in the `networks/nets` fold, here is the link https://github.com/Project-MONAI/MONAI/tree/dev/monai/networks/nets. Hope it can help you, thanks!

Thanks a lot, KumoLiu!!

But, unfortunately, I already found models in the networks/nets folder and use them.

And it also have problems like channel and size.

**Comment by KumoLiu** [comment]
Hi @SiYeon-Kwon, yes for different networks you may need to make some adjustments to some parameters (e.g. input and output channels) accordingly. Thanks!
