### ISSUE TITLE
Adopt PEP8 in MONAI/examples/notebooks/ 

### ISSUE THREAD

**Issue by Warvito** [Project-MONAI/tutorials#102]
**Is your feature request related to a problem? Please describe.**
Some notebooks are not following the PEP8 style guide.

**Describe the solution you'd like**
Please, consider following the PEP8 style guide in the notebooks from MONAI/examples/notebooks/.
For example, in [examples/notebooks/mednist_tutorial.ipynb](https://github.com/Project-MONAI/MONAI/blob/master/examples/notebooks/mednist_tutorial.ipynb), cell 4 has variables named using the CamelCase style instead snake_case (https://www.python.org/dev/peps/pep-0008/#id45), for example:

```
dataDir = './MedNIST/'
classNames = os.listdir(dataDir)
numClass = len(classNames)
```

Later, in the same notebook, the snake_case is adopted.

```
train_ds = MedNISTDataset(trainX, trainY, train_transforms)
train_loader = DataLoader(train_ds, batch_size=300, shuffle=True, num_workers=10)

val_ds = MedNISTDataset(valX, valY, val_transforms)
val_loader = DataLoader(val_ds, batch_size=300, num_workers=10)
```

**Comment by wyli** [comment]
addressed by #107
