### ISSUE TITLE
MRI Recon tutorial fail when batch_size>1

### ISSUE THREAD

**Issue by Can-Zhao** [Project-MONAI/tutorials#1020]
**Describe the bug**
MRI Recon tutorial fail when batch_size>1

**To Reproduce**
2. Install '....'
3. Run commands '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - Python version
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version
 - GPU models and configuration

**Additional context**

**Comment by wyli** [comment]
I think it's addressed by https://github.com/Project-MONAI/MONAI/issues/5886
