### ISSUE TITLE
Auto3DSeg notebook and markdown need improvement

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/tutorials#1047]
**Describe the bug**
Internal code review shows Auto3DSeg tutorials can be improved
- typo/bad sentences in notebooks
- some code snippet doesn't work
- notebooks failed on 8-GPU system
- inconsistent name/variables inside or between notebooks

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/1065
