### ISSUE TITLE
DynUNet needs updating for deep_supervision

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#106]
**Describe the bug**
Following [this PR](https://github.com/Project-MONAI/MONAI/pull/1393) to DynUNet, [the corresponding notebook](https://github.com/Project-MONAI/tutorials/blob/master/modules/dynunet_tutorial.ipynb) needs updating.

I tried simply removing `deep_supervision = True` from the constructor, but this wasn't enough.

The subsequent error is attached here: [dynunet.txt](https://github.com/Project-MONAI/tutorials/files/5808380/dynunet.txt).

@Nic-Ma I think you might best know what needs to be changed here.

**Comment by saruarlive** [comment]
Dear @Nic-Ma @rijobro et al,

The dynunet returns list (containing the output tensor). Had it returned a tensor in validation mode, it would have been easier to use.
So I changed a bit in the sliding window inference code to make it work. What do you think?
```
  #seg_prob = predictor(window_data, *args, **kwargs).to(device)  # batched patch segmentation
  seg_problist2tensor = predictor(window_data, *args, **kwargs)
  seg_prob = seg_problist2tensor[0] if isinstance(seg_problist2tensor, list) else seg_problist2tensor
  seg_prob = seg_prob.to(device)
```

**Comment by Nic-Ma** [comment]
I will have a try to run the notebook tomorrow, thanks for your issue report.

Thanks.

**Comment by rijobro** [comment]
Possibly best to make any changes in [this PR](https://github.com/Project-MONAI/tutorials/pull/107), as it will already have PEP8 modifications (and `git merge` is horrible wit jupyter notebooks)

**Comment by Nic-Ma** [comment]
Hi @saruarlive and @rijobro ,

I just submitted a commit to fix this issue in that branch: https://github.com/Project-MONAI/tutorials/pull/107/commits/c61cfd1cd02a2a2dea223d06ac2eed2d9ad1a929
@wyli , should we try to merge the notebook format PR ASAP? Otherwise, it's hard to develop new PRs and resolve conflicts.

Thanks.

**Comment by wyli** [comment]
> Hi @saruarlive and @rijobro ,
> 
> 
> 
> I just submitted a commit to fix this issue in that branch: https://github.com/Project-MONAI/tutorials/pull/107/commits/c61cfd1cd02a2a2dea223d06ac2eed2d9ad1a929
> 
> @wyli , should we try to merge the notebook format PR ASAP? Otherwise, it's hard to develop new PRs and resolve conflicts.
> 
> 
> 
> Thanks.
> 
> 

sure, could you please help review the changes? @Nic-Ma @yiheng-wang-nv @ericspod

**Comment by zedtran** [comment]
> Dear @Nic-Ma @rijobro et al,
> 
> The dynunet returns list (containing the output tensor). Had it returned a tensor in validation mode, it would have been easier to use.
> So I changed a bit in the sliding window inference code to make it work. What do you think?
> 
> ```
>   #seg_prob = predictor(window_data, *args, **kwargs).to(device)  # batched patch segmentation
>   seg_problist2tensor = predictor(window_data, *args, **kwargs)
>   seg_prob = seg_problist2tensor[0] if isinstance(seg_problist2tensor, list) else seg_problist2tensor
>   seg_prob = seg_prob.to(device)
> ```

@saruarlive This was helpful for me. I was finally able to get DynUNet working for the specified tutorial.

**Comment by yiheng-wang-nv** [comment]
Hi all, I just submitted a PR to update the DynUNet tutorial to meet the changes [here](https://github.com/Project-MONAI/MONAI/pull/1596). Now, the forward function will only return a single tensor (for both training and eval mode, with or without deep supervision).
