### ISSUE TITLE
Error in federated learning Substra tutorial

### ISSUE THREAD

**Issue by batbilguun44** [Project-MONAI/tutorials#1067]
Hello
We followed the tutorial in the link, and an error came out.
Will you please help us.
https://github.com/Project-MONAI/tutorials/tree/main/federated_learning/substra

Executed command:
DEBUG=True python scripts/run_in_substra.py

We are aware of issue 82 and tried 2 suggestions.
https://github.com/Project-MONAI/tutorials/issues/82
1. After uninstalling monai and itk, installed it with `pip install -q "monai[itk]”` command.
2. After uninstalling monai, installed it with `pip install [git+https://github.com/Project-MONAI/MONAI#egg=MONAI`](git+https://github.com/Project-MONAI/MONAI#egg=MONAI%60)

Config information:
from monai.config import print_config
print_config()
MONAI version: 1.0.0+123.g72130602
Numpy version: 1.21.6
Pytorch version: 1.12.1
MONAI flags: HAS_EXT = True, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 72130602340847e15f2042b2bb1b64f6f46eeb93
MONAI __file__: /opt/conda/lib/python3.7/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 4.0.2
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 9.2.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: 4.5.3
TorchVision version: 0.13.1+cu113
tqdm version: 4.64.1
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.9.3
pandas version: 1.3.5
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

The error:
Adding train dataset
Adding train data sample 1/40
Adding train data sample 2/40
Adding train data sample 3/40
Adding train data sample 4/40
Adding train data sample 5/40
Adding train data sample 6/40
Adding train data sample 7/40
Adding train data sample 8/40
Adding train data sample 9/40
Adding train data sample 10/40
Adding train data sample 11/40
Adding train data sample 12/40
Adding train data sample 13/40
Adding train data sample 14/40
Adding train data sample 15/40
Adding train data sample 16/40
Adding train data sample 17/40
Adding train data sample 18/40
Adding train data sample 19/40
Adding train data sample 20/40
Adding train data sample 21/40
Adding train data sample 22/40
Adding train data sample 23/40
Adding train data sample 24/40
Adding train data sample 25/40
Adding train data sample 26/40
Adding train data sample 27/40
Adding train data sample 28/40
Adding train data sample 29/40
Adding train data sample 30/40
Adding train data sample 31/40
Adding train data sample 32/40
Adding train data sample 33/40
Adding train data sample 34/40
Adding train data sample 35/40
Adding train data sample 36/40
Adding train data sample 37/40
Adding train data sample 38/40
Adding train data sample 39/40
Adding train data sample 40/40
Adding test dataset
Adding test data sample 1/5
Adding test data sample 2/5
Adding test data sample 3/5
Adding test data sample 4/5
Adding test data sample 5/5
Adding objective
Adding algo
Adding compute plan
Waiting for compute plan to finish

Execution logs: substratools.utils - Module 'opener' imported dynamically; module=<module 'opener' from '/sandbox/opener/__init__.py'>
substratools.opener - loading X from '['/sandbox/data/local_f7ce9e7ee23ea833dfaa824c0f28ace1143e522621563315c6e9843d6bc0435e', '/sandbox/data/local_32d97a6e8274a3db2ec8285e4a510b1bdb828581248f9559ca2545acd207e5f8', '/sandbox/data/local_f456641075f9abc5d7950cb43699090650e796ae08eea59c69eba53ba0794a45', '/sandbox/data/local_7b1ce536000398757e9467b43301f8202212735808267395615998912597ed0f', '/sandbox/data/local_3d074a2f1ba8863128f26881362205f47ddfdfb36b4923040352cd6eb10f0f11', '/sandbox/data/local_a2d943f21204be059b24a9586ad6b0c311229b3d26bc21b4d56568dbdf5d3739', '/sandbox/data/local_67d1d048dac9fce66501520c3a0826508cbcb9eb8954480f1df18d4921b6e717', '/sandbox/data/local_92d28d9032382842efec2fe8f1f0bfc2949201344ad731d1b5bbafb699110b7d', '/sandbox/data/local_1c548cfab4d35c31e03d5fbd0b8a47a857d1f28b8598e46f1979c7d201cfffe4', '/sandbox/data/local_88cd97d70a2e44dcee17a449fa055416e5572e33f49227637636005ca5ba153f', '/sandbox/data/local_e90466622ecd2295a6a0c8c8af2ab409b970216dbd7e3f5fc810dac0190bcd22', '/sandbox/data/local_bdbb54f5ab277a1706d7d500f6e9c36c22167b3274591f45145afe8d3a83352c', '/sandbox/data/local_a9b34516d901ad2043768914c595397a22bdd6e8393f6303aa146613c90a85ac', '/sandbox/data/local_36189de6f0fdedd56959c4a6bec3b58ef0f633d9d71567bc92f7e12adb14674f', '/sandbox/data/local_e7ceec1325294375314056c8f9a898e18ea3d8e7da4570547c408281fe249808', '/sandbox/data/local_0a81966aa97f93818f69fd80a7139d4ef2839ab861bca1d06f39a2b5602fe2ca', '/sandbox/data/local_1a88855e1f61dee34caee0f40c8084a488da65148472aa9e6f5ee15de3a977ac', '/sandbox/data/local_f723581b2a947a119f800d4a9bebf7c9b4bb0ab6fb784dfce223c427e68649de', '/sandbox/data/local_f84dcd8ad7dc99ddddd5a36a8983ad1b0fb49137d10aa67097d47017b58bb761', '/sandbox/data/local_6964496eb01262964bb3871429fbeb432ff7a72eae8c13c2d9d2aae5a5798d5e', '/sandbox/data/local_453a2a5363d8cea99a3d00c5a4be329853626b0e3572082ee1f86e61db7eb767', '/sandbox/data/local_7193e75837c0b600461d48be94a47d5335e8daae4be006801f92fdbece5104c6', '/sandbox/data/local_53d2e7ae90155b6ef3b389108bd2bc43e5ddccb392c676897b38e7d4d3068e81', '/sandbox/data/local_1de3a6dec4cdfb0826124b00ca265f667de8d136fb896d7d9c45cbbd8d95220f', '/sandbox/data/local_66895726bb3300877bf509af76e60b373875eb8a38bd3e953267a79225dbbf80', '/sandbox/data/local_586448782856768b21976502e8e5769c89526a38af9ac3427c8bc118a3dc2202', '/sandbox/data/local_daa5eeecc827b355c730fc7665a88735c86d2c7b74039c69b6b3ca2d20eba23d', '/sandbox/data/local_7edf5ef343bb106604dd0b6bc56af758a91335306904c8b7033fe5444f3edf9c', '/sandbox/data/local_c09c346cb1e3c58b9fc3da3e3a8c5f56fa793643f21fe41639527b9f33f3e947', '/sandbox/data/local_8f097d615534745d99d96c53dfd529c777bf7d60d5bf3136c8415934438ae046', '/sandbox/data/local_a0c0dff2980357356e272a7137adcc7af20d704f57d112766b07eca0e594a050', '/sandbox/data/local_08dac93e1f7ea0880e9f0e7062300650d0f074d4c87a41b556bcdb11745b0e16', '/sandbox/data/local_c5371ba21b21e0e98d7abc438cd6185b391fcf943d7772c630c922ef4abd6aef', '/sandbox/data/local_b73f5d306a8112630e456f228fa6c01ca552e19dee5e1d7180fda3aa4675990e', '/sandbox/data/local_12b1791f1938023199126226f6b7680c88fb89f12467ae8ab89517a59332fe26', '/sandbox/data/local_de6fef7274481caaed3e63142e198d0e81a22ff5b8d8b9b984973f77f44d483a', '/sandbox/data/local_6d882c9a43b19431ec8cdeab37c7d4c481cc09e1f1b6463bc75e6def0ec2a9e6', '/sandbox/data/local_3013a00a4ae6382d663c0756277b7438179ff7f61f5f58dcb8c2589fcee1a65e', '/sandbox/data/local_7f604d0411cb71a5f18c0b79aee80307259706d06d895215787ff65a4eb37bc2', '/sandbox/data/local_f6194ce2dfe1f8688efe599906add2a276d23dad93b4ec35b18a7442942f5ea0']'
/usr/local/lib/python3.6/dist-packages/monai/data/dataset.py:285: UserWarning: tqdm is not installed, will not show the caching progress bar.
  warnings.warn("tqdm is not installed, will not show the caching progress bar.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/utils.py", line 309, in apply_transform
    return transform(data)
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/io/dictionary.py", line 77, in __call__
    data = self._loader(d[key], reader)
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/io/array.py", line 103, in __call__
    img = reader.read(filename)
  File "/usr/local/lib/python3.6/dist-packages/monai/data/image_reader.py", line 145, in read
    img_.append(itk.imread(name, **kwargs_))
  File "/usr/local/lib/python3.6/dist-packages/monai/utils/module.py", line 207, in __getattr__
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/monai/utils/module.py", line 167, in optional_import
    pkg = __import__(module)  # top level module
monai.utils.module.OptionalImportError: import itk (No module named 'itk').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "algo.py", line 85, in <module>
    tools.algo.execute(MonaiAlgo())
  File "/usr/local/lib/python3.6/dist-packages/substratools/algo.py", line 1062, in execute
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/substratools/algo.py", line 348, in _train
    args.n_fake_samples
  File "/usr/local/lib/python3.6/dist-packages/substratools/algo.py", line 243, in train
    X = self._opener_wrapper.get_X(fake_data, n_fake_samples)
  File "/usr/local/lib/python3.6/dist-packages/substratools/opener.py", line 197, in get_X
    return self._interface.get_X(self.data_folder_paths)
  File "/sandbox/opener/__init__.py", line 63, in get_X
    loader = self._get_loader(folders)
  File "/sandbox/opener/__init__.py", line 50, in _get_loader
    ds = CacheDataset(data=files, transform=transforms)
  File "/usr/local/lib/python3.6/dist-packages/monai/data/dataset.py", line 298, in __init__
    self._cache[i] = self._load_cache_item(data[i], transform.transforms)
  File "/usr/local/lib/python3.6/dist-packages/monai/data/dataset.py", line 314, in _load_cache_item
    item = apply_transform(_transform, item)
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/utils.py", line 311, in apply_transform
    raise type(e)(f"Applying transform {transform}.").with_traceback(e.__traceback__)
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/utils.py", line 309, in apply_transform
    return transform(data)
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/io/dictionary.py", line 77, in __call__
    data = self._loader(d[key], reader)
  File "/usr/local/lib/python3.6/dist-packages/monai/transforms/io/array.py", line 103, in __call__
    img = reader.read(filename)
  File "/usr/local/lib/python3.6/dist-packages/monai/data/image_reader.py", line 145, in read
    img_.append(itk.imread(name, **kwargs_))
  File "/usr/local/lib/python3.6/dist-packages/monai/utils/module.py", line 207, in __getattr__
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/monai/utils/module.py", line 167, in optional_import
    pkg = __import__(module)  # top level module
monai.utils.module.OptionalImportError: Applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7fac06878c18>.

Traceback (most recent call last):
  File "scripts/run_in_substra.py", line 176, in <module>
    "testtuples": testtuples,
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/client.py", line 42, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/client.py", line 519, in add_compute_plan
    return self._backend.add(spec, exist_ok=False, spec_options=spec_options)
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/backend.py", line 885, in add
    asset = add_asset(key, spec, spec_options)
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/backend.py", line 514, in _add_compute_plan
    spec_options
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/backend.py", line 213, in __execute_compute_plan
    traintuple_key = self.add(traintuple_spec, exist_ok, spec_options)
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/backend.py", line 885, in add
    asset = add_asset(key, spec, spec_options)
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/backend.py", line 593, in _add_traintuple
    self._worker.schedule_traintuple(traintuple)
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/compute/worker.py", line 205, in schedule_traintuple
    container_name, str(algo.content.storage_address), command, volumes=volumes
  File "/opt/conda/lib/python3.7/site-packages/substra/sdk/backends/local/compute/spawner.py", line 85, in spawn
    raise ExecutionError(f"Container '{name}' exited with status code '{exit_code}'")
substra.sdk.backends.local.compute.spawner.ExecutionError: Container 'algo-local_f25f53461472789f8a75dc1ac049f4d8a42ab26bbece1b59f3492540adb059fe' exited with status code '1'

**Comment by wyli** [comment]
please try `pip install itk`,  looks like the error is still about not able to locate itk `monai.utils.module.OptionalImportError: import itk (No module named 'itk').`

**Comment by batbilguun44** [comment]
@wyli 
thank you for your reply.
we already tried `pip install itk` , but still getting the same error.

**Comment by wyli** [comment]
I had another look, probably the system environment is messed up, because the traceback messages are not from the same python... `/usr/local/lib/python3.6` and `/opt/conda/lib/python3.7`. 

monai dropped py3.6 support since version 0.8...

this demo is created with monai v0.3.0 https://github.com/Project-MONAI/tutorials/blob/9d86a38b5bfd18296444863d79288b6ae9c0a6da/federated_learning/substra/assets/algo/Dockerfile#L8

unlikely it'll work with monai 1.0, and we won't be able provide further maintenance at the moment...
