### ISSUE TITLE
setup github action for code format checks

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#108]
this is a followup of https://github.com/Project-MONAI/tutorials/pull/107
to run basic checks such as autopep8  isort with github action 
 see also
https://github.com/Project-MONAI/MONAI/blob/ec70d9637d7b3be4b3266c0060df25d08e0b6ecd/.github/workflows/pythonapp.yml#L15-L42

**Comment by rijobro** [comment]
I've added an attempt in the [non-interactive PR](https://github.com/rijobro/tutorials/blob/noninteractive_run/.github/workflows/pep8.yml). This will run the pep8 check (hopefully, untested!).

For the execution of the notebooks, we could do some sort of `git diff` to only execute notebooks that have been modified. See this [stackoverflow answer](https://stackoverflow.com/a/57862507/12411867).

**Comment by wyli** [comment]
thanks @rijobro if you push the changes to `your-fork/master`, it'll trigger the check. e.g. https://github.com/wyli/tutorials/runs/1777386617

**Comment by rijobro** [comment]
Thanks, seems to be working now! https://github.com/rijobro/Tutorials/runs/1777424979?check_suite_focus=true

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/107
