### ISSUE TITLE
How to use MONAI - Unet with 2D images in png format

### ISSUE THREAD

**Issue by acamargosonosa** [Project-MONAI/tutorials#1091]
Hi there, 
I am trying to use Unet from MONAI to train it with 2D png data, I am following the idea of this code:
https://github.com/Project-MONAI/tutorials/tree/main/2d_segmentation/torch

My png images are have dimension of 512 x 512, are in gray scale (they come from Ultrasound device)

The transforms that I am using are:  
train_imtrans = Compose(
    [
        LoadImaged(keys=["img", "seg"]),
        AddChanneld(keys=["img", "seg"]),
        ScaleIntensityd(keys=["img", "seg"]),
        RandCropByPosNegLabeld(
            keys=["img", "seg"], label_key="seg", spatial_size=[96, 96], pos=1, neg=1, num_samples=4
            ),
        RandRotate90d(keys=["img", "seg"], prob=0.5, spatial_axes=[0, 1]),
        EnsureTyped(keys=["img", "seg"]),
        ]
    )
val_transforms = Compose(
    [
        LoadImaged(keys=["img", "seg"]),
        AddChanneld(keys=["img", "seg"]),
        ScaleIntensityd(keys=["img", "seg"]),
        EnsureTyped(keys=["img", "seg"]),
        ]
    )

val_imtrans = Compose([LoadImage(image_only=True, ensure_channel_first=True), ScaleIntensity()])
val_segtrans = Compose([LoadImage(image_only=True, ensure_channel_first=True), ScaleIntensity()])

# define array dataset, data loader
check_ds = ArrayDataset(images, train_imtrans, segs, train_segtrans)
check_loader = DataLoader(check_ds, batch_size=10, num_workers=2, pin_memory=torch.cuda.is_available())

im, seg = monai.utils.misc.first(check_loader)

I am getting this error:
=======================================================
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1277572/3049765578.py in <module>
----> 1 im, seg = monai.utils.misc.first(check_loader)
      2 #print(im.shape, seg.shape)

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/utils/misc.py in first(iterable, default)
     83     Returns the first item in the given iterable or `default` if empty, meaningful mostly with 'for' expressions.
     84     """
---> 85     for i in iterable:
     86         return i
     87     return default

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    679                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    680                 self._reset()  # type: ignore[call-arg]
--> 681             data = self._next_data()
    682             self._num_yielded += 1
    683             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1374             else:
   1375                 del self._task_info[idx]
-> 1376                 return self._process_data(data)
   1377 
   1378     def _try_put_index(self):

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1400         self._try_put_index()
   1401         if isinstance(data, ExceptionWrapper):
-> 1402             data.reraise()
   1403         return data
   1404 

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    459             # instantiate since we don't know how to
    460             raise RuntimeError(msg) from None
--> 461         raise exception
    462 
    463 

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py", line 91, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py", line 55, in _apply_transform
    return transform(parameters)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/io/array.py", line 239, in __call__
    img = reader.read(filename)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/image_reader.py", line 267, in read
    img_.append(itk.imread(name, **kwargs_))
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/itk/support/extras.py", line 1293, in imread
    reader = template_reader_type.New(**kwargs)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/itk/support/template_class.py", line 662, in New
    itk.ImageFileReader, False, "FileName", *args, **kwargs
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/itk/support/template_class.py", line 161, in _NewImageReader
    f"Could not create IO object for reading file {inputFileName}" + msg
RuntimeError: Could not create IO object for reading file image
The file doesn't exist. 
Filename = image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py", line 91, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py", line 55, in _apply_transform
    return transform(parameters)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py", line 118, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.array.LoadImage object at 0x7f59adab2590>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py", line 1318, in __getitem__
    return self.dataset[index]
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py", line 105, in __getitem__
    return self._transform(index)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py", line 1215, in _transform
    data.extend(to_list(dataset[index]))
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py", line 105, in __getitem__
    return self._transform(index)
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py", line 91, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/sonosa/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py", line 118, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f59adab2850>

**Comment by ericspod** [comment]
For your first try you should be using `Dataset` and not `ArrayDataset`, it looks like you've mixed code between the array and dictionary versions of the examples. The dictionary transforms (those ending with `d`) should be used with `Dataset` which is given a list of dictionaries containing filenames keyed to "image" and "label" as input. 

For your second try the network should be set to accept three channel inputs since you're reading RGB, so `in_channels=3` in your constructor for the UNet.

**Comment by acamargosonosa** [comment]
Thanks a lot Eric for your response, but when I changed the in_channels  and out_channels to 3 (because it I leaving out_channels to 1) there was also a similar error,

config = {
    # data
    "cache_rate": 1.0,
    "num_workers": 2,


    # train settings
    "train_batch_size": 2,
    "val_batch_size": 1,
    "learning_rate": 1e-3,
    "max_epochs": 100, # it was 100
    "val_interval": 10, # check validation score after n epochs
    "lr_scheduler": "cosine_decay", # just to keep track




    # Unet model (you can even use nested dictionary and this will be handled by W&B automatically)
    "model_type": "unet", # just to keep track
    "model_params": dict(spatial_dims=3,
                  in_channels=3,
                  out_channels=3,
                  channels=(16, 32, 64, 128, 256),
                  strides=(2, 2, 2, 2),
                  num_res_units=2,
                  norm=Norm.BATCH,
    )
}

``
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_1373955/1893856992.py in <module>
     22         optimizer.zero_grad()
     23         outputs = model(inputs)
---> 24         loss = loss_function(outputs, labels)
     25         loss.backward()
     26         optimizer.step()

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/losses/dice.py in forward(self, input, target)
    144                 warnings.warn("single channel prediction, `to_onehot_y=True` ignored.")
    145             else:
--> 146                 target = one_hot(target, num_classes=n_pred_ch)
    147 
    148         if not self.include_background:

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/networks/utils.py in one_hot(labels, num_classes, dtype, dim)
    151 
    152     if sh[dim] != 1:
--> 153         raise AssertionError("labels should have a channel with length equal to one.")
    154 
    155     sh[dim] = num_classes

AssertionError: labels should have a channel with length equal to one.

**Comment by acamargosonosa** [comment]
I think that I can solve the problem converting my input images to gray scale, how can I do that ?

**Comment by ericspod** [comment]
Change only `in_channels` to 3, leave `out_channels` as the number of classes you want to predict, or 1 if it's binary. If you want to convert to greyscale you might want to use command line tools to make a new dataset such as imagemagick.

**Comment by acamargosonosa** [comment]
When I do use in_channels to 3 and out_channels to 1, (because I only want to predict the segmentation of 1 tissue).  I am getting this error:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_1376077/1893856992.py in <module>
     22         optimizer.zero_grad()
     23         outputs = model(inputs)
---> 24         loss = loss_function(outputs, labels)
     25         loss.backward()
     26         optimizer.step()

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/losses/dice.py in forward(self, input, target)
    144                 warnings.warn("single channel prediction, `to_onehot_y=True` ignored.")
    145             else:
--> 146                 target = one_hot(target, num_classes=n_pred_ch)
    147 
    148         if not self.include_background:

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/networks/utils.py in one_hot(labels, num_classes, dtype, dim)
    151 
    152     if sh[dim] != 1:
--> 153         raise AssertionError("labels should have a channel with length equal to one.")
    154 
    155     sh[dim] = num_classes

AssertionError: labels should have a channel with length equal to one.

**Comment by acamargosonosa** [comment]
My question about rgb to gray is because, my images are in png format, so maybe monai assumes that it in rgb and sets the channels to 3, but the images have a dimension of 512x512 (like a gray scale image). So, I was thinking, if I convert the images using monai to gray scale, the problem could be solved.

**Comment by ericspod** [comment]
You could convert manually using a `Lambdad` and a function that does the conversion, one of these [solutions would work](https://stackoverflow.com/questions/12201577/how-can-i-convert-an-rgb-image-into-grayscale-in-python) but you have to keep in mind that your channel dimension will be first rather than last as expected here. I think you also need to look at how many channels your label images have, it seems they have 3 which implies three classes but if you want to do binary segmentation these need to have 1 channel only as well so they need converting.

**Comment by acamargosonosa** [comment]
Pardon, the output when I used in_channels to 3, leave out_channels to 1 (binary classifier), I am getting this error:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_1376077/1893856992.py in <module>
     22         optimizer.zero_grad()
     23         outputs = model(inputs)
---> 24         loss = loss_function(outputs, labels)
     25         loss.backward()
     26         optimizer.step()

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/losses/dice.py in forward(self, input, target)
    155 
    156         if target.shape != input.shape:
--> 157             raise AssertionError(f"ground truth has different shape ({target.shape}) from input ({input.shape})")
    158 
    159         # reducing only spatial dimensions (not batch nor channels)

AssertionError: ground truth has different shape ((8, 3, 96, 96)) from input ((8, 1, 96, 96))

**Comment by ericspod** [comment]
Yes so your ground truth is 3 channel, you need to convert them to 1 channel if you have only 1 class. I have looked up what the transform would look like, something like this would work:

```python
def _convert(image):
    r, g, b = image
    gray = 0.2989 * r + 0.5870 * g + 0.1140 * b
    return gray[None,...]

rgb_to_gray= Lambdad(["image","seg"],_convert)
```

If you use that after loading your image and label pairs and adding a channel that should convert both to grayscale.

**Comment by ericspod** [comment]
`Lambdad` is a transform so it doesn't have a shape, I had meant it should be used in your transform sequence:

```python
train_imtrans = Compose(
    [
        LoadImaged(keys=["img", "seg"]),
        Lambdad(["im","seg"],_convert),
        ScaleIntensityd(keys=["img", "seg"]),
    ...
    ]
)
```

**Comment by acamargofb** [comment]
Thanks a lot for your reply, but when I do that I am getting this error:
Just in case the images are in tensor format of size (8,3,96,96)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items, log_stats)
     90             return [_apply_transform(transform, item, unpack_items) for item in data]
---> 91         return _apply_transform(transform, data, unpack_items)
     92     except Exception as e:

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py in _apply_transform(transform, parameters, unpack_parameters)
     54 
---> 55     return transform(parameters)
     56 

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/utility/dictionary.py in __call__(self, data)
   1039         for key, func, overwrite in self.key_iterator(d, self.func, self.overwrite):
-> 1040             ret = self._lambd(img=d[key], func=func)
   1041             if overwrite:

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/utility/array.py in __call__(self, img, func)
    831             raise TypeError(f"func must be None or callable but is {type(fn).__name__}.")
--> 832         out = fn(img)
    833         # convert to MetaTensor if necessary

/tmp/ipykernel_1877514/4105821486.py in _convert(image)
      1 def _convert(image):
----> 2     r, g, b = image
      3     gray = 0.2989 * r + 0.5870 * g + 0.1140 * b

ValueError: too many values to unpack (expected 3)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items, log_stats)
     90             return [_apply_transform(transform, item, unpack_items) for item in data]
---> 91         return _apply_transform(transform, data, unpack_items)
     92     except Exception as e:

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py in _apply_transform(transform, parameters, unpack_parameters)
     54 
---> 55     return transform(parameters)
     56 

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/compose.py in __call__(self, input_)
    172         for _transform in self.transforms:
--> 173             input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
    174         return input_

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items, log_stats)
    117                 _log_stats(data=data)
--> 118         raise RuntimeError(f"applying transform {transform}") from e
    119 

RuntimeError: applying transform <monai.transforms.utility.dictionary.Lambdad object at 0x7fdd2ac62750>

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1877514/1179077659.py in <module>
      1 check_ds = Dataset(data=val_files, transform=val_transforms)
      2 check_loader = DataLoader(check_ds, batch_size=1)
----> 3 check_data = first(check_loader)
      4 image, label = (check_data["image"][0][0], check_data["label"][0][0])
      5 print(f"image shape: {image.shape}, label shape: {label.shape}")

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/utils/misc.py in first(iterable, default)
     83     Returns the first item in the given iterable or `default` if empty, meaningful mostly with 'for' expressions.
     84     """
---> 85     for i in iterable:
     86         return i
     87     return default

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    679                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    680                 self._reset()  # type: ignore[call-arg]
--> 681             data = self._next_data()
    682             self._num_yielded += 1
    683             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    719     def _next_data(self):
    720         index = self._next_index()  # may raise StopIteration
--> 721         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    722         if self._pin_memory:
    723             data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

~/anaconda3/envs/monai/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py in __getitem__(self, index)
    103             # dataset[[1, 3, 4]]
    104             return Subset(dataset=self, indices=index)
--> 105         return self._transform(index)
    106 
    107 

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/data/dataset.py in _transform(self, index)
     89         """
     90         data_i = self.data[index]
---> 91         return apply_transform(self.transform, data_i) if self.transform is not None else data_i
     92 
     93     def __getitem__(self, index: Union[int, slice, Sequence[int]]):

~/anaconda3/envs/monai/lib/python3.7/site-packages/monai/transforms/transform.py in apply_transform(transform, data, map_items, unpack_items, log_stats)
    116             else:
    117                 _log_stats(data=data)
--> 118         raise RuntimeError(f"applying transform {transform}") from e
    119 
    120 

RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7fdd2ac62e50>

**Comment by ericspod** [comment]
THe `_convert` function I gave above assumes the first dimension has 3 channels for RGB. Your image has dimension (8,3,96,96) it seems. Your transform sequence is meant to work on one image at a time so if that dimension represents a  batch of 8 images you need to break that up and process your data in a different way somehow.
