### ISSUE TITLE
brats_segmentation_3d data loader taking too long

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#110]
**Describe the bug**
The data loader here is taking over an hour to load the 100 images: https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/brats_segmentation_3d.ipynb. Running on MONAI's master branch.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

Maybe your device is not very powerful? You can decrease the `cache_num`.
If still taking same time, maybe need to check whether we have a bug.

Thanks.

**Comment by rijobro** [comment]
I don't think that's the problem unfortunately, as I'm running on a 32GB V100. Num workers is set to 4 by default, which we could increase, but it's hard to see that having a dramatic reduction in computation time. Does the code run quickly for you? I'm currently trying to run it in colab, but it has to download the 7GB of data first.

**Comment by rijobro** [comment]
Ah possibly an IO problem on my cluster, sorry!
