### ISSUE TITLE
Broken linnk 

### ISSUE THREAD

**Issue by sergeicu** [Project-MONAI/tutorials#113]
Link to VAE tutorial: 

https://github.com/Project-MONAI/tutorials/blob/master/README.md#varautoencoder_mednist

Produces 404 error. 

Page moved?

**Comment by rijobro** [comment]
Hi, and thanks! 
Looks like the link is missing the `.ipynb` extension. I'll add that now. Just in case you need it, the proper link is:
https://github.com/Project-MONAI/tutorials/blob/master/modules/varautoencoder_mednist.ipynb
