### ISSUE TITLE
How to modify the train_cache_rate parameter through the configuration file

### ISSUE THREAD

**Issue by wojiazaiyugang** [Project-MONAI/tutorials#1131]
I am using auto3dseg for segmentation experiments, my running script is
```python
from monai.apps.auto3dseg import AutoRunner

if __name__ == '__main__':
    runner = AutoRunner(input={"name": "Task500_XXX",
                                "task": "segmentation",
                                "modality": "CT",
                                "datalist": "/home/XXX/Projects/MONAI/dataset.json",
                                "dataroot": "/media/DATA2/XXX/20221124/",
                                "class_names": ["upper", "lower"]},
                        work_dir="/home/XXX/Projects/MONAI/work_dir",
                        analyze=True,
                        algo_gen=True)
    runner.run()
```
First, there is no problem with generating dataset.yaml by dataset analysis, and then there is no problem with generating algorithm. Next, start training and run the file work_dir/dints_0/scripts/search.py
After a period of time, the machine has a memory overflow and the program is killed (my machine has 128G memory)
After looking at the code, I suspect that it is caused by data caching
https://github.com/Project-MONAI/research-contributions/blob/1dde7a112c69785b4fb5cd58d5b73f3fa5bdc577/auto3dseg/algorithm_templates/dints/scripts/search.py#L168
My data has about 300 copies of CT data, and they cannot all be cached.
I want to know how to modify this parameter, I tried to modify input.yaml or runner.set_train_param() ,but it didn’t work

**Comment by wojiazaiyugang** [comment]
i try add this , but not work
```python
    runner.set_training_params({
        "train_cache_rate": 0.2
    })
```

After tracking the code, I found that the train.py of dints will change the parameter train_cache_rate into searching#train_cache_rate(https://github.com/Project-MONAI/research-contributions/blob/1dde7a112c69785b4fb5cd58d5b73f3fa5bdc577/auto3dseg/algorithm_templates/dints/scripts/algo.py#L395), but in search.py, it still parses train_cache_rate(https://github.com/Project-MONAI/research-contributions/blob/1dde7a112c69785b4fb5cd58d5b73f3fa5bdc577/auto3dseg/algorithm_templates/dints/scripts/search.py#L162) to obtain the default value of 1. Is there something I overlooked?

**Comment by mingxin-zheng** [comment]
Hi @wojiazaiyugang , thanks for the issue. I think you are using the code in the right way, and this is a bug that needs to be fixed.

Does your environment accept doing an export before running the program? If yes, I can probably help fixing this quickly for you.

cc @dongyang0122 for vis.

**Comment by mingxin-zheng** [comment]
Hi @wojiazaiyugang , an update: I prepared a [pull request](https://github.com/Project-MONAI/research-contributions/pull/173) for the team's review. 
While reviewers need time to check, the fix is available for you if you can use a `ALGO_HASH` to download the fix:

```bash
ALGO_HASH=3f56d77 python <your .py script>
```


`runner.set_training_params({"cache_rate": 0.2})` seems working fine to me.

**Comment by wojiazaiyugang** [comment]
Hi @mingxin-zheng 
Thank you very much for the quick reply~ By the way, is there any official plan to add some simple verification functions or documents or tutorials for auto3dseg, such as a document that discloses all parameters that can be overridden and their functions. At the same time, if there is a problem with the parameters provided by the user, an error can be reported (at least a warning). Because the auto3dseg process is relatively complicated, it is often difficult for users to track the code to see how a parameter takes effect. A completely free input.yaml will worry about whether it really takes effect after writing each parameter.

**Comment by mingxin-zheng** [comment]
Thank you! This is in discussion and you're more than welcome to suggest one or multiple features for the team to pick up!

[Submit a feature in MONAI](https://github.com/Project-MONAI/MONAI/issues/new/choose)
