### ISSUE TITLE
The bug of brats_segmentation_3d

### ISSUE THREAD

**Issue by Achillesy** [Project-MONAI/tutorials#1138]
The EnsureTyped function is missing in val_org_transforms, which may cause unknown errors in lower versions of Monai 0.9.0

**Comment by KumoLiu** [comment]
Hi @Achillesy, we recommend using metatensor from version 0.9.1, which is why `EnsureTyped` was removed. If you are using an earlier version, you can add `EnsureTyped` or change the tutorial tag to 0.9.0 to see the earlier versions of the tutorial.
