### ISSUE TITLE
Add tests to check formats

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/tutorials#1143]
The new contributing guidelines list several requirements that need to be integrated in our GitHub actions.

**Is your feature request related to a problem? Please describe.**

Tests/actions to be added:
- [x] license/copyright check for scripts and notebooks
- [ ] standard cell block such as setup environment and setup imports
- [ ] output text limit length
- [x] DCO

**Comment by mingxin-zheng** [comment]
Since most notebooks do not have the copyright headers, I think we need to make these checks optional in the beginning, revise all notebooks/source code, and finally, enforce the checks as "required".

**Comment by wyli** [comment]
before finishing this ticket, I think we can enable the precommit auto formatting: https://github.com/Project-MONAI/tutorials/pull/1110. the required code change to config the tool is here https://github.com/Project-MONAI/tutorials/pull/1110/commits/6e072302688819564dd540fa06d9fdad5d9e8847

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Should we move the toolkit things back to this repo first[WIP]? Then auto formatting?

Thanks.
