### ISSUE TITLE
Registration tutorial

### ISSUE THREAD

**Issue by kate-sann5100** [Project-MONAI/tutorials#115]
**Is your feature request related to a problem? Please describe.**
There is no registration tutorial in this repository.

**Describe the solution you'd like**
Add a registration tutorial for paired ct lung registration.

**Describe alternatives you've considered**
N/A

**Additional context**
DeepReg paired ct lung registration [demo](https://github.com/DeepRegNet/DeepReg/tree/main/demos/paired_ct_lung)

**Comment by ebrahimebrahim** [comment]
Is there a registration tutorial now?
