### ISSUE TITLE
Multiple Instance Learning: SplitDimd TypeError: __init__() got an unexpected keyword argument 'list_output'

### ISSUE THREAD

**Issue by JunMa11** [Project-MONAI/tutorials#1153]
**Describe the bug**

Dear MONAI, 

I'm using the default code for MIL but running into the following error

https://github.com/Project-MONAI/tutorials/blob/main/pathology/multiple_instance_learning/README.md

```python
    SplitDimd(keys=["image"], dim=0, keepdim=False, list_output=True),
TypeError: __init__() got an unexpected keyword argument 'list_output'
```

The error is a little bit wired since this function has the `list_output` variable

https://github.com/Project-MONAI/MONAI/blob/c5ea694985dc1e8eeef075da3a65b2c2fc2f9a8e/monai/transforms/utility/dictionary.py#L385-L398

The interesting thing is that the training pipeline works after removing this variable `SplitDimd(keys=["image"], dim=0, keepdim=False)`

Any comments are highly appreciated. 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.9
 - MONAI version: 1.1
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: A5500 24G

**Comment by JunMa11** [comment]
Is this the typo for a_min and a_max?

https://github.com/Project-MONAI/tutorials/blob/e5a1876ec41be44ac7185b07768177110c316f52/pathology/multiple_instance_learning/panda_mil_train_evaluate_pytorch_gpu.py#L296

It should be `a_min=np.float32(0), a_max=np.float32(255)`, right?

**Comment by KumoLiu** [comment]
Hi @JunMa11, the first problem is that maybe you have multiple versions of MONAI, could you please check the environment you are running?
Also thanks for pointing out the typo, I will create a PR to fix it!

**Comment by JunMa11** [comment]
Yes, you are right!!! 

The 1st problem has been solved by installing monai in a fresh enviroment. Thank you so much.

**Comment by JunMa11** [comment]
Hi @KumoLiu 

Is there any out-of-the-box function or API to generate the following heatmap figure? Fig 3b

The figure is from the corresponding paper in the MIL tutorial

https://arxiv.org/abs/2111.01556

![image](https://user-images.githubusercontent.com/19947331/211937145-f65ee571-047b-4ae3-a14b-7d67bfaadcbe.png)

**Comment by KumoLiu** [comment]
Hi @JunMa11, you could use `ProbMapProducer` which is a handler to generate probability maps. If you are using this [tutorial](https://github.com/Project-MONAI/tutorials/blob/main/pathology/multiple_instance_learning/panda_mil_train_evaluate_pytorch_gpu.py), maybe simply save the output. Thanks!
https://github.com/Project-MONAI/MONAI/blob/fdd07f36ecb91cfcd491533f4792e1a67a9f89fc/monai/handlers/probability_maps.py#L32

Seems we didn't have a tutorial for this handler, maybe we could add it later. cc @drbeh.
