### ISSUE TITLE
Use monai-weekly throughout

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#119]
Since the pep8 refactor, we check if monai is installed, and install it if not:

```
!python -c "import monai" || pip install -q "monai[pillow, tqdm]"
```

We should really be using a more up-to-date version of monai, so should probably switch to using `monai-weekly` throughout:
```
!python -c "import monai" || pip install -q "monai-weekly[pillow, tqdm]"
```

**Comment by wyli** [comment]
addressed by https://github.com/Project-MONAI/tutorials/pull/133 please file new tickets for any follow-up
