### ISSUE TITLE
Compare results in `dataset_type_performance.ipynb`

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/tutorials#1214]
**Is your feature request related to a problem? Please describe.**
From the results of [this comparison experiment](https://github.com/Project-MONAI/tutorials/blob/1.0.0/acceleration/dataset_type_performance.ipynb), why the time of `CacheDataset` is slower than `PersistentDataset` for each epoch of training? Users may not easily understand the advantages of `CacheDataset` from these results.

![image](https://user-images.githubusercontent.com/55491388/218407910-23829aff-266c-4174-ab71-ad1153260848.png)

**Describe the solution you'd like**
The results in tag 1.0.0 are more make sense.
![image](https://user-images.githubusercontent.com/55491388/218408518-f58514a3-8a31-4ebb-b12e-e8994dd2f4e1.png)
 
cc @wyli @Nic-Ma

**Comment by wyli** [comment]
maybe the persistent dataset was created before the experiments, so it's faster? in that case they are not fair comparisons, it's introduced by this PR https://github.com/Project-MONAI/tutorials/pull/1179 cc @dongyang0122 @mingxin-zheng  do you have time to have a look?

**Comment by dongyang0122** [comment]
hi @KumoLiu, what computing hardware did you use to generate the first figure? I list the specs of the computing environment used for the second figure as follows. It might be related to CPU capacities.

GPU: A100, 80GB RAM
CPU: AMD 64-Core 2.6 GHz Processor, 1T RAM

**Comment by KumoLiu** [comment]
Hi @dongyang0122, the first figure is in the dev branch which as Wenqi mentioned is introduced by this [PR](https://github.com/Project-MONAI/tutorials/pull/1179). Thanks!

**Comment by dongyang0122** [comment]
@KumoLiu Thanks for confirming that! I re-run the tutorial today, and I can reproduce the result. Moreover, I run the old tutorial notebook with the same conclusion. We may need more information on PersistentDataset and CacheDataset.
