### ISSUE TITLE
dicom

### ISSUE THREAD

**Issue by shahriar-faghani** [Project-MONAI/tutorials#123]
**Please use MONAI's Discussions tab**
For questions relating to MONAI usage, please do not create an issue.

Instead, use [MONAI's GitHub Discussions tab](https://github.com/Project-MONAI/MONAI/discussions). This can be found on the MONAI repository's main page (not the tutorials) next to Issues and Pull Requests along the top.

**Comment by rijobro** [comment]
Closing this as it is an empty issue.
