### ISSUE TITLE
deepedit ignite uses the same pre-transforms in training and validation

### ISSUE THREAD

**Issue by yexincheng** [Project-MONAI/tutorials#1233]
Dear MONAI teams,

Thanks for your great work!

I was running the tutorial of deepedit ignite. I found that the validation dice metrics were decreasing during training but the training dice increased. 
Then I noticed the validation dataloader's pre-transforms are the same as the training's ([https://github.com/Project-MONAI/tutorials/blob/main/deepedit/ignite/train.py/#L189]). But there are several random transforms, which I guess will impact the validation dice.

**Comment by tangy5** [comment]
yes, it could because the validation used the same pretransforms which contains the random data augmentations. I would suggest that you can create a separate pre_transforms which remove those randFlip,   RandRotate90d,  RandShiftIntensityd, etc...
