### ISSUE TITLE
3d registration tutorial on my own dataset

### ISSUE THREAD

**Issue by agatadefr** [Project-MONAI/tutorials#1247]
Hello, 

I am trying to follow your 3D registration tutorial. I tested on lungs dataset and it is working fine. 
But Yesterday I wanted to apply to my own dataset liver. I created the same pipeline and structured data but I got an error 
**ValueError("the data to aggregate must be PyTorch Tensor.")**

MONAI version: 1.1.0
Numpy version: 1.21.5
Pytorch version: 1.13.1+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__: /home/.local/lib/python3.9/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
Nibabel version: 5.0.0
scikit-image version: 0.19.2
Pillow version: 9.2.0
Tensorboard version: 2.12.0
gdown version: 4.6.3
TorchVision version: 0.14.1+cu117
tqdm version: 4.64.1
lmdb version: 1.4.0
psutil version: 5.9.0
pandas version: 1.4.4
einops version: 0.6.0
transformers version: 4.26.1
mlflow version: 2.1.1
pynrrd version: 1.0.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

/projects/test_monai_registration/MONAI_DATA_DIRECTORY
moving_image shape: torch.Size([96, 96, 104]), moving_label shape: torch.Size([96, 96, 104])
fixed_image shape: torch.Size([96, 96, 104]), fixed_label shape: torch.Size([96, 96, 104])

Loading dataset:   0%|          | 0/4 [00:00<?, ?it/s]
Loading dataset:  25%|â–ˆâ–ˆâ–Œ       | 1/4 [01:57<05:51, 117.31s/it]
Loading dataset: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 [01:57<00:00, 29.33s/it] 
/home//.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/.local/lib/python3.9/site-packages/monai/networks/blocks/warp.py:66: UserWarning: monai.networks.blocks.Warp: Using PyTorch native grid_sample.
  warnings.warn("monai.networks.blocks.Warp: Using PyTorch native grid_sample.")
Traceback (most recent call last):
  File "/projects/test_monai_registration/monai_image_registration_liver.py", line 219, in <module>
    metric = dice_metric.aggregate().item()
  File "/home/.local/lib/python3.9/site-packages/monai/metrics/meandice.py", line 99, in aggregate
    raise ValueError("the data to aggregate must be PyTorch Tensor.")
ValueError: the data to aggregate must be PyTorch Tensor.

How could I fixed this ? 
What can be a problem ? Could you help me please ?

**Comment by KumoLiu** [comment]
Hi @agatadefr, could you please check the type of `dice_metric(y_pred=val_pred_label, y=val_fixed_label)`? From the error message seems the type before the aggregate is wrong.
Thanks!

**Comment by wyli** [comment]
came across a similar issue recently -- make sure the validation set inputs are not empty

**Comment by rekalantar** [comment]
There is definitely something going wrong in your code, have you double-checked if the normalisation and data prep are as expected? That's a common source of error

**Comment by KumoLiu** [comment]
Hi @rekalantar, which tutorial did you refer to?
