### ISSUE TITLE
Update `model_zoo` and `bundle` to follow `BundleWorkflow`

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/tutorials#1266]
**Is your feature request related to a problem? Please describe.**
As we already introduced the new `BundleWorkflow` API in MONAI 1.2, need to update the `model_zoo` tutorials and `bundle` tutorials to follow it.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

BTW, please also check every bundle related tutorials to avoid "MONAI model zoo" description, because we will also include it in the toolkit for NGC bundles.

Thanks.

**Comment by yiheng-wang-nv** [comment]
Update: I'm now working on this ticket.
