### ISSUE TITLE
Box coordinates wrong in example LUNA data?

### ISSUE THREAD

**Issue by AceMcAwesome77** [Project-MONAI/tutorials#1278]
I'm looking at file 1.3.6.1.4.1.14519.5.2.1.6279.6001.308655308958459380153492314021.nii.gz in LUNA16_Images_resample.  If I call that file "f" and print the header using the following:

scan = nibabel.load(f)
print(scan.header)

I see these values for the offsets:

qoffset_x       : -145.70703
qoffset_y       : -2.7070312
qoffset_z       : -386.6

However if I look in the provided LUNA box coordinates for that study I see this:

		{
            "box": [
                [
                    -46.88603145,
                    -71.47201601,
                    -204.7362163,
                    5.253505195,
                    5.253505195,
                    5.253505195
                ],
                [
                    -85.90557458,
                    -179.9071501,
                    -108.8742678,
                    5.100020792,
                    5.100020792,
                    5.100020792
                ]
            ],
            "image": "1.3.6.1.4.1.14519.5.2.1.6279.6001.308655308958459380153492314021/1.3.6.1.4.1.14519.5.2.1.6279.6001.308655308958459380153492314021.nii.gz",
            "label": [
                0,
                0
            ]
        },

How can the center y-coordinates of both those boxes be less than -70, when the y offset is only -2?  It's my understanding that the offsets represent the origin corner voxel.  Wouldn't the box coordinates be way outside the image then?

**Comment by Nic-Ma** [comment]
Hi @Can-Zhao ,

Could you please help share some comments here?

Thanks in advance.

**Comment by Can-Zhao** [comment]
It is world coordinate, provided by original LUNA dataset. The world coordinate system is different from image coordinate which we might expect for. The unit is 1mm, not pixel/voxel. The origin is also different. That is why there is a transform `AffineBoxToImageCoordinated` that converts world coordinate to image coordinate.

**Comment by AceMcAwesome77** [comment]
Thanks for the reply - I am still having trouble with this though.  Say I wanted to take the example LUNA data, and print out some JPEG images with the boxes overlaid on the images, to better visualize the original data.  (The reason for this is I then want to do the same operation to my own data, to make sure my real dataset boxes are in the same coordinate space as the example data).

If I load an example LUNA nifti file into a numpy array like this:

scan = nib.load(f)
voxels = scan.get_fdata()

Now I have a "voxels" array with shape (464, 464, 240).  How would I properly convert the provided annotation boxes so that I can overlay them on the image?  (I already have code to draw the boxes).   Here is what I tried before:

    xmin = box[0] - (box[3] / 2) - scan.header['qoffset_x']
    xmax = box[0] + (box[3] / 2) - scan.header['qoffset_x']
    ymin = box[1] - (box[4] / 2) - scan.header['qoffset_y']
    ymax = box[1] + (box[4] / 2) - scan.header['qoffset_y']
    zmin = box[2] - (box[5] / 2) - scan.header['qoffset_z']
    zmax = box[2] + (box[5] / 2) - scan.header['qoffset_z']

where "box" is the array of length 6 from the annotation json file [xcenter, ycenter, zcenter, xdiameter, ydiameter, zdiameter].

This is where I ran into the original problem where my calculated ymin was negative.  How do I transform this box into all positive coordinates so they can be properly overlaid on this nifti array of voxels?  Thanks!

**Comment by AceMcAwesome77** [comment]
Also, just to be sure I am getting this right from your previous comment, is this correct:

LUNA dataset boxes (example: [ -46.88603145, -71.47201601,  -204.7362163,  5.253505195,  5.253505195,  5.253505195] are in WORLD coordinates

LUNA dataset nifti header offsets (example: qoffset_x : -145.70703, qoffset_y: -2.7070312, qoffset_z: -386.6) are in IMAGE coordinates

These numbers are for studyUID = 1.3.6.1.4.1.14519.5.2.1.6279.6001.308655308958459380153492314021

**Comment by Can-Zhao** [comment]
I was wondering if you could try the following transform. if the following code does not give reasonable box coordinates, it means the MONAI code has bug.

```
train_transforms = Compose(
        [
            LoadImaged(keys=[image_key], meta_key_postfix="meta_dict"),
            EnsureChannelFirstd(keys=[image_key]),
            EnsureTyped(keys=[image_key, box_key], dtype=torch.float32),
            EnsureTyped(keys=[label_key], dtype=torch.long),
            StandardizeEmptyBoxd(box_keys=[box_key], box_ref_image_keys=image_key),
            Orientationd(keys=[image_key], axcodes="RAS"),
            intensity_transform,
            EnsureTyped(keys=[image_key], dtype=torch.float16),
            ConvertBoxToStandardModed(box_keys=[box_key], mode=gt_box_mode),
            AffineBoxToImageCoordinated(
                box_keys=[box_key],
                box_ref_image_keys=image_key,
                image_meta_key_postfix="meta_dict",
                affine_lps_to_ras=True,
            ),
    ]
```

**Comment by Can-Zhao** [comment]
Maybe the key reason is with `affine_lps_to_ras=True`. The way you computed box coordinate assumes `affine_lps_to_ras=False`, which is true for most data, but not true for this data.

**Comment by AceMcAwesome77** [comment]
Where is function StandardizeEmptyBoxd imported from?  I don't see that anywhere in the monai code or documentation.

**Comment by Can-Zhao** [comment]
> Where is function StandardizeEmptyBoxd imported from? I don't see that anywhere in the monai code or documentation.

Oh, you can remove that line. It is in dev branch. Removing it won't affect your work

**Comment by AceMcAwesome77** [comment]
Thanks again for the answers.  Do you know if there is any function in monai to save images with the training boxes on them after preprocessing but before training, for visualization, to make sure sure the boxes are in the right place following all the preprocessing?

**Comment by Can-Zhao** [comment]
We don't have it in monai core code. But I wore it in tutorial. https://github.com/Project-MONAI/tutorials/blob/57ad05373b5aac6c7b26484463309a68eac20cc3/detection/luna16_training.py#L349

**Comment by AceMcAwesome77** [comment]
I guess the simplest form of my question is this.  I am trying to use my own custom data where I don't have information about the original coordinate space.  Therefore I want my origin to be at 0,0,0 and all my bounding box annotation values to be positive.  What would a proper json file with these coordinates look like if this was the box I was trying to define?

![image](https://user-images.githubusercontent.com/97188850/230483580-95f5efbe-f79d-4c94-9a09-fad4fac72897.png)

Here is how I would currently put the training box coordinates for this example image.  Is this wrong?

"box": [
                [
                    7.0,
                    2.0,
                    15.0,
                    2.0,
                    2.0,
                    2.0
                ]

**Comment by Can-Zhao** [comment]
I see, so your box is already in image coordinate, then you won't need to convert it from world coordinate. Maybe try this code:
```
train_transforms = Compose(
        [
            LoadImaged(keys=[image_key], meta_key_postfix="meta_dict"),
            EnsureChannelFirstd(keys=[image_key]),
            EnsureTyped(keys=[image_key, box_key], dtype=torch.float32),
            EnsureTyped(keys=[label_key], dtype=torch.long),
            Orientationd(keys=[image_key], axcodes="RAS"),
            EnsureTyped(keys=[image_key], dtype=torch.float16),
            ConvertBoxToStandardModed(box_keys=[box_key], mode=gt_box_mode),
    ]
```

**Comment by AceMcAwesome77** [comment]
I deleted this comment a few seconds before the above reply, so I will repost it here so the response makes sense; this entry should go above Can-Zhao's reply.

- I guess the simplest form of my question is this. I am trying to use my own custom data where I don't have information about the original coordinate space. Therefore I want my origin to be at 0,0,0 and all my bounding box annotation values to be positive. What would a proper json file with these coordinates look like if this was the box I was trying to define?
 
Here is how I would currently put the training box coordinates for this example image. Is this wrong?
"box": [
[
7.0,
3.0,
15.0,
2.0,
2.0,
2.0
]

**Comment by AceMcAwesome77** [comment]
Update: it appears I finally got this working, as my dataset boxes appear in the right place on the tensorboard printout.  There were 3 things I needed to do to achieve this with my dataset.

1) Remove the AffineBoxToImageCoordinated from my preprocessing transforms like you said.

2) Set the affine matrix to the eye matrix with affine=np.eye(4).  I had originally used the voxel size values of 0.703125, 0.703125, 1.25 in the affine matrix to match the example LUNA data - but I do not actually need to do this if I am already in image coordinates.

3) Flip the X and Y coordinates of my annotated bounding boxes.  I don't yet understand why this made it work, but this was a necessary step.  For example, in my picture above, this would be the proper bounding box coordinates in the json file, where you can see the 3.0 and 7.0 have switched:
[
3.0,
7.0,
15.0,
2.0,
2.0,
2.0
]

I would also flip the first two "2.0" values if they were not equal.  After doing these three things, my dataset boxes appear in the correct place at the visualize_one_xy_slice_in_3d_image() step.

Thanks for the timely help Can-Zhao!

**Comment by Can-Zhao** [comment]
Happy to know you fixed it! Yes, x-y axis are switched in https://github.com/Project-MONAI/tutorials/blob/57ad05373b5aac6c7b26484463309a68eac20cc3/detection/visualize_image.py#L53

I will add a bool variable to switch between Cartesian indexing and Matrix indexing  in the future.

Thank you for reporting this!

**Comment by AceMcAwesome77** [comment]
Ok, that explains why the XY flip is needed on my initial annotation boxes then.  I am using python and numpy for nifti file and mask generation which uses Cartesian indexing.  I then converted the masks into boxes which left them in Cartesian coordinates.  Great to know, thanks!

**Comment by KumoLiu** [comment]
> tutorials/detection/luna16_training.py

Hi @dyollb, the box is already there, you can see how the data looks like mentioned [here](https://github.com/Project-MONAI/tutorials/issues/1278#issue-1653010495).
Hope it helps, thanks.

**Comment by dyollb** [comment]
Thanks, i figured it out and even managed to get it working on my data: 
https://github.com/dyollb/anatomical-landmark-detection
