### ISSUE TITLE
Error when running 'DynUNet' tutorial:  object has no attribute 'get_feature_maps'

### ISSUE THREAD

**Issue by DrAlaafeef** [Project-MONAI/tutorials#128]
**Describe the bug**

I tried to run this tutorial, and I got this error message:
"torch.nn.modules.module.ModuleAttributeError: 'DynUNet' object has no attribute 'get_feature_maps'"
This error showed when runing the docker images "projectmonai/monai:0.4.0" and 2projectmonai/monai:latest".

It seems to me that the DynUNet public interface "get_feature_maps method" was deleted and updated with a concatenated tensor. However, the tutorial still not updated.

Please only create issues here relating to the functioning of the tutorials. For all other questions/problems/bugs, please refer to MONAI's [main repository](https://github.com/Project-MONAI/MONAI). For MONAI bugs (not just a problem in the notebook), please create an [issue](https://github.com/Project-MONAI/MONAI/issues). For questions, please use the [Discussions tab](https://github.com/Project-MONAI/MONAI/discussions).

**Comment by rijobro** [comment]
Thanks for raising this!

**Comment by wyli** [comment]
the multiscale features have been updated to be stacked:
https://github.com/Project-MONAI/MONAI/blob/06e1e990b03a763ac0a1da0e37917f991e3901cf/monai/networks/nets/dynunet.py#L207-L211
