### ISSUE TITLE
Add training tutorials of generative models

### ISSUE THREAD

**Issue by Warvito** [Project-MONAI/tutorials#1294]
Add a few tutorials from MONAI Generative Models for a better visibility. We plan to add the following:

- [x] #1358
- [ ] [2D DDPM](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_ddpm/2d_ddpm_tutorial.ipynb)
- [ ] [3D DDPM](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/3d_ddpm/3d_ddpm_tutorial.ipynb)
- [ ] [2D VQVAE+Transformer](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_vqvae_transformer/2d_vqvae_transformer_tutorial.ipynb)
- [ ] [VQGAN](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_vqgan/2d_vqgan_tutorial.ipynb)

**Comment by ericspod** [comment]
We're going to move this list over to #1769.
