### ISSUE TITLE
Breaking change loss function in the reconstruction tutorial.

### ISSUE THREAD

**Issue by binliunls** [Project-MONAI/tutorials#1349]
**Describe the bug**
Because of [this PR](https://github.com/Project-MONAI/MONAI/pull/6250), there is a breaking change in the `SSIMLoss`. Unfortunatelly, this loss is used in the [varnet reconstruction demo](https://github.com/Project-MONAI/tutorials/blob/45bf2f19886218a52e2843434b8ac53a8c694d0f/reconstruction/MRI_reconstruction/varnet_demo/train.py#L141) . Therefore, this tutorial must be updated according to this change.

**To Reproduce**
1. Start a MONAI 1.2.0rc5 docker
1. Following the README file in the [varnet reconstruction demo](https://github.com/Project-MONAI/tutorials/tree/main/reconstruction/MRI_reconstruction/varnet_demo) to setup the dataset.
2. Run commands
```
python ./train.py\
    --data_path_train train_dir \
    --data_path_val val_dir \
    --exp varnet_mri_recon \
    --exp_dir ./ \
    --mask_type equispaced \
    --num_epochs 50 \
    --num_workers 0 \
    --lr 0.00001
```

**Expected behavior**
Start to train.

**Screenshots**

```
  File "/workspace/tutorials/monai/reconstruction/MRI_reconstruction/varnet_demo/train.py", line 186, in trainer
    loss = loss_function(output_crp, tar, max_value)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given
```

**Environment (please complete the following information):**
 - Python version: 3.8.10
 - MONAI version 1.2.0rc5
 - CUDA: 12.1

**Comment by binliunls** [comment]
Hi @Can-Zhao ,
    Could you please help to take a loot at this issue? I saw the `data_range` parameter of the loss changed every iteration in the reconstruction code. However, the new version loss just initialized it once in the `__init__` function.  I don't know if there is a graceful way to adapt the new version of `SSIMLoss` in the reconstruction code.

Thanks,
Bin

**Comment by wyli** [comment]
that's discussed here https://github.com/Project-MONAI/MONAI/issues/6267#issuecomment-1493311944

**Comment by wyli** [comment]
I think one way to fix it is to create the loss later in the pipeline https://github.com/Project-MONAI/tutorials/pull/1351 (untested)
