### ISSUE TITLE
demo script for singe image inference

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#136]
**Is your feature request related to a problem? Please describe.**
the current inference/evaluation pipelines are all based on a set of images (list of filenames, dataset, dataloader etc...),
would be great to have a simple script for running model inference/evaluation of one data sample.

**Comment by talhaanwarch** [comment]
First you have to load image using PIL, nibabel.
For example if you have 2D image, it will be read as (512,512)
Then add an extra dimension at axis 0, (1,512,512)
Pass it through model(image)

**Comment by talhaanwarch** [comment]
If it still need, i can write a script

**Comment by wyli** [comment]
this is also a good example https://github.com/Project-MONAI/tutorials/pull/595
