### ISSUE TITLE
error when running monailabel for nodule detection

### ISSUE THREAD

**Issue by monaalsh** [Project-MONAI/tutorials#1379]

**Comment by monaalsh** [comment]
I get the following error after running monailabel with bundle model nodule detection 

`monailabel start_server --app apps/monaibundle --studies datasets/Task06_Lung/imagesTr --conf models lung_nodule_ct_detection`

below in the error I get

[2023-05-10 08:13:15,982] [70122] [MainThread] [ERROR] (uvicorn.error:56) - Application startup failed. Exiting.

**Comment by KumoLiu** [comment]
Hi @monaalsh, [here](https://github.com/Project-MONAI/MONAILabel/discussions) would be a better place to raise this discussion. I will close this one. Thanks!
