### ISSUE TITLE
Cannot import name 'Batch' from 'torchtext.data'

### ISSUE THREAD

**Issue by anoukstein** [Project-MONAI/tutorials#139]
**Describe the bug**
On running the tutorial for 3D Spleen segmentation with Pytorch lightning, the error message 'cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)' is displayed because Batch is in a legacy file.
**To Reproduce**
Reproduce by running the tutorial import section.

**Environment (please complete the following information):**
Colab Pro, GPU

**Comment by ericspod** [comment]
This appears to be an incompatibility in the version of Lightning specified in the notebook. If you remove "==0.9.0" from the pip line that installs it you will get the most recent version which might work with this notebook. I'm not sure if we've tested with that version yet but we're working on getting automated testing for these notebooks going. Do try this and let us know if that works for you or not.

**Comment by anoukstein** [comment]
That worked! Thank you! Best, Anouk
