### ISSUE TITLE
ROI size sliding window

### ISSUE THREAD

**Issue by kissievendor** [Project-MONAI/tutorials#14]
Hi,
I was wondering how UNet deals with the sliding window input. 
Because the ROI you set is bigger than the patches UNet is trained on. 
How does this work? 

Thanks.
Kirsten

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Could you please help explain something in theory from the researcher aspect?

Thanks.

**Comment by YuanTingHsieh** [comment]
From what I understand, UNet is consists of CNNs.
So it can take input of different shape.
Like you trained it in [96, 96, 96], but you can inference it in [160,160,160] cubes.

The advantage of inference it using larger cubes is that you get faster inference speed.

Please correct me if I am wrong @wyli

**Comment by kissievendor** [comment]
Thank you. Do you have some sort of article? Because everything I am reading suggest to use same size. Also, when using a larger sliding window, my results can differ dramatically.
