### ISSUE TITLE
Update 3d_segmentation tutorials COVID-19-20 challenge baseline

### ISSUE THREAD

**Issue by xiaofang007** [Project-MONAI/tutorials#1428]
Hi, I notice that NiftiSaver is deprecated since MONAI 0.8.0 and is removed in MONAI 1.2.0. However, I try to use monai.transforms.SaveImage to replace NiftiSaver but it seems that Nibabel image saver reports error that the 'affine' parameter needs to be 2D but in meta data it is 3D. Thanks (I am not sure whether I use SaveImage correctly).

**Comment by wyli** [comment]
thanks for reporting this, please consider the changes here:
https://github.com/Project-MONAI/MONAI/commit/127e823dc52224e3b201679b16c5d76e9c57e2ab#diff-dafbabeacb7a0e855e5dda2b895603006099a7265762165302005a727872c320
![Screenshot 2023-06-18 at 15 32 50](https://github.com/Project-MONAI/tutorials/assets/831580/5550d712-d8b0-45c9-9a55-29938601e502)

(the example baseline needs an update to use SaveImage. https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/challenge_baseline/run_net.py)
