### ISSUE TITLE
MONAI bundle developers guide for the pytorch users

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#1456]
**Is your feature request related to a problem? Please describe.**
bundle templates, minimal examples for bundle workflow for pytorch users to get started migrating existing workflows
- 90% use cases typical template bundle, so that they don't start from scratch
- available on model-zoo

(see also ideas like https://github.com/cookiecutter/cookiecutter)

**Comment by ericspod** [comment]
Template for segmentation bundle is here now: https://github.com/Project-MONAI/model-zoo/pull/514 This partially addresses this issue.
