### ISSUE TITLE
Detection tutorial - files in dataset_fold0.json do not match the downloaded subset0.zip from LUNA16

### ISSUE THREAD

**Issue by jhairgallardo** [Project-MONAI/tutorials#1543]
I am trying to run the detection tutorial for LUNA16 using the mhd files downloaded from the LUNA dataset website. To prototype faster, I have only downloaded the subset0.zip that can be found here https://zenodo.org/record/3723295 . I noticed that the json file provided in the tutorial for fold 0 inside the mhd_original folder (dataset_fold0.json) do not match the files I got from the subset0.zip, causing an error of "file not found". (For example, the json file has the SUID 1.3.6.1.4.1.14519.5.2.1.6279.6001.250397690690072950000431855143 but that one is not inside the subset0.zip from LUNA)
am I missing something here? 
Thank you in advance

**Comment by diazandr3s** [comment]
Hi @jhairgallardo,

Are you familiar with 3DSlicer? Have you tried using MONAI Label and the [detection bundle](https://github.com/Project-MONAI/model-zoo/tree/dev/models/lung_nodule_ct_detection)? I'd recommend you give a try to that.
Here are the instructions: https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/monaibundle#detection-model

Use this sample dataset: https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/monaibundle#step-3-prepare-sample-data

Let us know how that goes

**Comment by KumoLiu** [comment]
Hi @jhairgallardo, you can find the dataset_fold0.json in this section in the README.
https://github.com/Project-MONAI/tutorials/tree/main/detection#1-data

Hope it helps, thanks!

**Comment by jhairgallardo** [comment]
Thank you. I downloaded the complete dataset instead (the copy in the detection tutorial) and everything works now.
