### ISSUE TITLE
unable to open the monai_101.ipynb notebook under the 2d_classification section

### ISSUE THREAD

**Issue by deepakri201** [Project-MONAI/tutorials#1569]
Hi, 

I'm trying to open the **monai_101.ipynb** notebook in the 2d_classification section. I can open it in GitHub, but when I click on the `"Open in Colab"` button, the notebook fails to open:

![image](https://github.com/Project-MONAI/tutorials/assets/59979551/da8b3ed6-07b8-43d8-b4a8-ba32deb2ce7c)

Thank you! 

Deepa

**Comment by KumoLiu** [comment]
Hi, @deepakri201, thanks for reporting this issue.
There is a typo in the link that may need to be fixed.
