### ISSUE TITLE
swin_unetr_btcv_segmentation_3d: pre trained model download link broken

### ISSUE THREAD

**Issue by dyollb** [Project-MONAI/tutorials#1672]
**Describe the bug**

In the [swin_unetr_btcv_segmentation_3d](https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/swin_unetr_btcv_segmentation_3d.ipynb) there are some links to download the pre-trained model. Unfortunately, these links are broken.

**To Reproduce**
1. Go to [swin_unetr_btcv_segmentation_3d](https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/swin_unetr_btcv_segmentation_3d.ipynb)
2. Check the download for the pre-trained model (including wget commands)

**Expected behavior**
The download links are updated.

**Comment**
It seems some weights can be downloaded in the research contribution repo:
- https://github.com/Project-MONAI/research-contributions/tree/main/SwinUNETR/BTCV
- but the file is 3x smaller than the file I downloaded some months ago, when the link worked (?)

**Comment by KumoLiu** [comment]
Hi @dyollb, thanks for your interest here.

The link works for me. Could you please try:
`wget -O ./dataset_0.json 'https://drive.google.com/uc?export=download&id=1qcGh41p-rI3H_sQ0JwOAhNiQSXriQqGi'`
Perhaps the reason is that you don't have a folder named data.

Thanks.

**Comment by dyollb** [comment]
As I wrote in my report I am talking about the model weights, e.g.

![image](https://github.com/Project-MONAI/tutorials/assets/12702862/dfd34b89-664f-4947-88e4-f903ab9581c0)

and here

![image](https://github.com/Project-MONAI/tutorials/assets/12702862/339c28a5-7cec-4d39-9fd7-16802d449546)

**Comment by dyollb** [comment]
My bad: seems I copied the wget url incorrectly, but the other link is broken...

![bad_link_monai_tutorial](https://github.com/Project-MONAI/tutorials/assets/12702862/34751316-6519-4646-ab15-5c627e260186)
