### ISSUE TITLE
Incorporating ONNX Support into Brain Tumor Segmentation Example

### ISSUE THREAD

**Issue by ctongh** [Project-MONAI/tutorials#1681]
**Is your feature request related to a problem? Please describe.**
In our development endeavors, we've leveraged the robust capabilities of the MONAI library, facilitating rapid progress in our projects. However, our usage scenario spans across diverse platforms, prompting us to opt for ONNX to store our model parameters and utilize ONNX Runtime for inference. 

**Describe the solution you'd like**
Upon reviewing the monai/tutorial repository, we found a lack of examples incorporating ONNX or similar technologies. Thus, we've crafted a simple example based on the **`brats_segmentation_3d`** to demonstrate the disparate output results of different models.

We're keen to contribute this code snippet to monai—happy to contribute!

**Comment by Kbinn** [comment]
I'd like to ask how it's going. I'm in need of it.
