### ISSUE TITLE
please upload more famous diffusion model about image to image，thanks

### ISSUE THREAD

**Issue by qianxiaqiyue** [Project-MONAI/tutorials#1705]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KumoLiu** [comment]
Hi @qianxiaqiyue, we are now trying to move these models into the core. The development is in the gen-ai-dev branch.
https://github.com/Project-MONAI/GenerativeModels/tree/main/generative/networks/nets

Thanks.
