### ISSUE TITLE
monailabel tutorials contain broken and outdated links to Orthanc

### ISSUE THREAD

**Issue by wow64cpu** [Project-MONAI/tutorials#1718]
**Describe the bug**
The notebook _MONAI Label Radiology App - OHIF Spleen Segmentation Example_ contains invalid download links for Orthanc and plugins for it. Because of this, the contents of the executable files contain the HTML of the page of the Orthanc download directory, where the outdated link redirects, as a result of this, the server does not start and it is not possible to configure the environment according to the instructions.

**To Reproduce**
1. Go to `monailabel/monailabel_radiology_spleen_segmentation_OHIF.ipynb`
2. Try run step _2. Setup Orthanc DICOM Server_ 

**Expected behavior**
The server is expected to start successfully on **http://127.0.0.1:8042**

**Screenshots**
![image](https://github.com/Project-MONAI/tutorials/assets/44067368/d2cd6235-6f61-4fcb-b848-5b69e9d09fef)

**Environment (please complete the following information):**
 - Ubuntu 22.04.3 LTS
 - Python 3.10.12

**Comment by ericspod** [comment]
@diazandr3s would you be able to have a look at this? Thanks!

**Comment by wow64cpu** [comment]
I made a pull request https://github.com/Project-MONAI/tutorials/pull/1719
