### ISSUE TITLE
What need to do if some training slices are all background?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [Project-MONAI/tutorials#174]
N foreground 0, N  background 1325572, unable to generate class balanced samples.

**Comment by rijobro** [comment]
which tutorial?

**Comment by GOZGOXGOYGO** [comment]
My code is from the 2d segmentation tutorial. For the reason that the training slices are from a 3D volume, some slices don't have any target. Training with such dataset, the MONAI network reports this.

**Comment by KeqingWu** [comment]
Did you solve this problem? I also encountered the same problem.Looking forward to receiving your reply, thank you!

**Comment by alfonsostg** [comment]
@GOZGOXGOYGO, @KeqingWu check your label data. It should be int16 ranging 0-1.
