### ISSUE TITLE
Index embedding of MAISI

### ISSUE THREAD

**Issue by Z7Gao** [Project-MONAI/tutorials#1764]
I tried to write the unconditional sampler of MAISI myself and found the body region embeddings confusing.
Since the body region index is currently obtained from a mask (`get_body_region_index_from_mask`), what should `top_region_index_tensor` and `bottom_region_index_tensor` be when doing unconditional sampling?

@guopengf @Can-Zhao

**Comment by guopengf** [comment]
Hi, the diffusion unet is trained to condition the body region and spacing. As explained in this [tutorial](https://github.com/Project-MONAI/tutorials/blob/main/generative/maisi/maisi_diff_unet_training_tutorial.ipynb), "The body regions are formatted as 4-dimensional one-hot vectors: the head and neck region is represented by [1,0,0,0], the chest region by [0,1,0,0], the abdomen region by [0,0,1,0], and the lower body region (below the abdomen) by [0,0,0,1]. " The top/bottom region index roughly reflects where the CT scan cut-off is.  For example, when `top_region_index_tensor` is [1,0,0,0] and `bottom_region_index_tensor` is  [0,0,1,0], the generated image should cover from the head neck region to the abdomen region.

**Comment by Can-Zhao** [comment]
> Hi, the diffusion unet is trained to condition the body region and spacing. As explained in this [tutorial](https://github.com/Project-MONAI/tutorials/blob/main/generative/maisi/maisi_diff_unet_training_tutorial.ipynb), "The body regions are formatted as 4-dimensional one-hot vectors: the head and neck region is represented by [1,0,0,0], the chest region by [0,1,0,0], the abdomen region by [0,0,1,0], and the lower body region (below the abdomen) by [0,0,0,1]. " The top/bottom region index roughly reflects where the CT scan cut-off is. For example, when `top_region_index_tensor` is [1,0,0,0] and `bottom_region_index_tensor` is [0,0,1,0], the generated image should cover from the head neck region to the abdomen region.

@dongyang0122 These seems to be important parameters to explain for users as they do not exist in standard diffusion model. I was wondering if you would like to expand it in tutorial?
