### ISSUE TITLE
Using auto3dseg for Multichannel Inputs

### ISSUE THREAD

**Issue by Yasna-frn** [Project-MONAI/tutorials#1773]
I'm trying to use auto3dseg for lesion segmentation and I've tried to make a JSON file like the Hecktor 22 example in this [link](https://github.com/Project-MONAI/tutorials/tree/main/auto3dseg/tasks/hecktor22). But it assumes the number of input channels is 1.

When I tried to make a JSON file like the BraTS JSON file (https://drive.google.com/file/d/1i-BXYe-wZ8R9Vp3GXoajGyqaJ65Jybg1/view) and defined:
runner = AutoRunner(
    work_dir="./work_dir_2ch",
    input={
        "modality": ["Ph1", "Ph3"],
        "datalist": "./ISPY_2Ch.json",
        "dataroot": "",
    },
It gives this error:
![image](https://github.com/user-attachments/assets/5fc09147-9341-4a26-b8c1-ba0f49dce940)

I'm wondering how I should use auto3dseg for multichannel inputs?

**Comment by diazandr3s** [comment]
Hi @Yasna-frn,

I know it can be confusing. But if you've created the JSON file as shown for BRATS daatset, you don't need to specify the modalities in the AutoRunner. Please remove this line:

`"modality": ["Ph1", "Ph3"],`

You can see [here](https://github.com/Project-MONAI/tutorials/blob/1c942f49693131c53365359a7b11153a563a97a6/auto3dseg/tasks/hecktor22/input.yaml#L1-L7) the arguments for HECTOR challenge and [here ](https://www.synapse.org/Synapse:syn51156910/discussion/threadId=10371) the arguments for BRATS.

Hope this helps,

**Comment by Yasna-frn** [comment]
Thank you! It's working now!

**Comment by diazandr3s** [comment]
Closing issue
