### ISSUE TITLE
tag/release a version of this repo for project-monai/monai v0.5.1

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#178]
**Is your feature request related to a problem? Please describe.**
v0.5.0 is released https://github.com/Project-MONAI/MONAI/tree/0.5.1
would be great to select and tag a corresponding tutorial release

**Comment by wyli** [comment]
I think we could check out a new release branch, replace all the pip install commands with `pip install monai==0.5.1` and then tag a milestone. or should we go for a gitflow approach (https://github.com/Project-MONAI/MONAI/issues/2041) for this repo as well? cc @Nic-Ma  @ericspod @rijobro

**Comment by ericspod** [comment]
Gitflow is maybe a bit too complicated for this repo, we don't anticipate making a lot of changes and it's not a dependent of other things. We should set the install command to be for the most recent released version of MONAI and whenever a new release goes out we need to check all the notebooks and increment their versions. 
The alternative is to set existing notebooks as `monai>=0.5.1` and leave those alone, new notebooks needing new features would have later versions as their minimum. This starts fragmenting what version notebooks rely on but if people have to use a specific older version of MONAI there will be notebooks they can run with it to test it works at the very least.
