### ISSUE TITLE
Dynet pipeline: problems with launching and tutorial

### ISSUE THREAD

**Issue by davidiommi** [Project-MONAI/tutorials#180]
Hello,

I have the following error messages when launching the dynet pipeline (Hippocampus multi and single gpu):

![Cattura](https://user-images.githubusercontent.com/38066083/114716395-4d8eda80-9d34-11eb-9395-6e314945793c.PNG)

I tried also the heart dataset and it cannot can't even find the cudnn

My machine:
 - OS Ubuntu 18.04
 - MONAI version 0.5.0, download of the docker MONAI
 - CUDA 11.2
 - GPU model: Tesla v100 (4 stations)

With the latest monai and 0.4.0 there are also problems with importing the libraries.

If you could change the previous ipynb file of the dynet, because now gives the 404 error (no page found). So we are sure to install the correct version and we are typing the right command for each training passage

Thanks in advance

**Comment by wyli** [comment]
thanks for reporting, could you help confirm the fixes? the latest tutorial repo should work with monai 0.5.0

**Comment by davidiommi** [comment]
Hi, I have still the same error, by training with the task 04: AttributeError: OPTIMIZER_COMPLETED

I simply downloaded the docker with the 0.5.0 monai version but it's not working. I also tried to install monai with pip but it gives the same error.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please verify and help on this ticket?

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
> Hi, I have still the same error, by training with the task 04: AttributeError: OPTIMIZER_COMPLETED
> 
> I simply downloaded the docker with the 0.5.0 monai version but it's not working. I also tried to install monai with pip but it gives the same error.

Hi @davidiommi , I pulled the latest docker and run task 04 with 1 and 2 gpus, and I did not meet errors. Could you please print monai version and post here? I submitted a PR (#197 ) and you can pull the latest code, and rerun the script to check the versions.

The following is my running versions:
MONAI version: 0.5.0+23.g898d073

**Comment by davidiommi** [comment]
Dear @yiheng-wang-nv,

I tried even with installing directly the github repository, but it's still not working. Maybe there is a problem with our machine 
![Cattura](https://user-images.githubusercontent.com/38066083/116058201-e18b6b00-a67f-11eb-8b7e-206696f2b97f.PNG)
(url)

This is the same error for task 4. For task 2 it does not even launch because it does not have enough GPU memory, even if we have 4 Nvidia Tesla. 

I am still able to use your implementation of nnUnet from the previous tutorial notebook, which now is not online anymore. So this is not a big deal for me. I would like to suggest only two things to improve the dynet:

- If you could please add dropout as an option. (I noticed I can have overfitting during training)
- If you could write more in the documentation about the output features maps from "deep supervision". (Suggestions how to set the weights for the features maps from each channel to compute the loss and which channel/output is the correct one to select for computation of dice and save the image). I would appreciate it a lot.

Thanks for the great work.
