### ISSUE TITLE
Official OcclusionSensitivity example is not workable

### ISSUE THREAD

**Issue by bbb801** [Project-MONAI/tutorials#183]
Dear Sir, 

The example of OcclusionSensitivity in your example is not workable(https://docs.monai.io/en/latest/visualize.html?highlight=OcclusionSensitivity).

**Run:**
# densenet 3d
from monai.networks.nets import DenseNet
from monai.visualize import OcclusionSensitivity

model_3d = DenseNet(spatial_dims=3, in_channels=1, out_channels=3, init_features=2, growth_rate=2, block_config=(6,))
occ_sens = OcclusionSensitivity(nn_module=model_3d, n_batch=10, stride=2)
occ_map, most_probable_class = occ_sens(torch.rand(1, 1, 6, 6, 6), class_idx=1, b_box=[-1, -1, 2, 3, -1, -1, -1, -1])

**Error:**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-911d4972e82b> in <module>
      5 model_3d = DenseNet(spatial_dims=3, in_channels=1, out_channels=3, init_features=2, growth_rate=2, block_config=(6,))
      6 occ_sens = OcclusionSensitivity(nn_module=model_3d, n_batch=10, stride=2)
----> 7 occ_map, most_probable_class = occ_sens(torch.rand(1, 1, 6, 6, 6), class_idx=1, b_box=[-1, -1, 2, 3, -1, -1, -1, -1])

TypeError: __call__() got an unexpected keyword argument 'class_idx'

**When I deleted 'class_idx', I still had an error:**

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-2f71a4cda0d2> in <module>
      5 model_3d = DenseNet(spatial_dims=3, in_channels=1, out_channels=3, init_features=2, growth_rate=2, block_config=(6,))
      6 occ_sens = OcclusionSensitivity(nn_module=model_3d, n_batch=10, stride=2)
----> 7 occ_map, most_probable_class = occ_sens(torch.rand(1, 1, 6, 6, 6), b_box=[-1, -1, 2, 3, -1, -1, -1, -1])

/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/monai/visualize/occlusion_sensitivity.py in __call__(self, x, b_box)
    297 
    298             # Generate sensitivity images
--> 299             sensitivity_ims_list, output_im_shape = self._compute_occlusion_sensitivity(x, b_box)
    300 
    301             # Loop over image for each classification

/environment/python/versions/miniconda3-4.7.12/lib/python3.7/site-packages/monai/visualize/occlusion_sensitivity.py in _compute_occlusion_sensitivity(self, x, b_box)
    218             raise ValueError(
    219                 "Stride and mask size should both be odd or even (element-wise). "
--> 220                 + f"``stride={self.stride}``, ``mask_size={self.mask_size}``"
    221             )
    222 

ValueError: Stride and mask size should both be odd or even (element-wise). ``stride=[1 2 2 2]``, ``mask_size=[ 1 15 15 15]``

I have used the corresponding version Monai. 
![image](https://user-images.githubusercontent.com/52306405/114966767-d37e6300-9ea5-11eb-8b8d-dc515ebd9b7b.png)

**Comment by rijobro** [comment]
Hi, which tutorial is this? We use occlusion sensitivity in our [covid classification](https://github.com/Project-MONAI/tutorials/blob/master/modules/interpretability/covid_classification.ipynb) tutorial, and as far as I can tell, this is currently running successfully (see today's [cron log](https://github.com/Project-MONAI/MONAI/runs/2359076260?check_suite_focus=true#step:6:581)).

Could you try running the notebook as-is, without any modifications? You'll also need to make sure that you're using a verion of `monai` and `monai-tutorials` that are from the same time. E.g., you could use `0.4.0` for both, or `0.5.0` of `monai` and `master` of `monai-tutorials` (since we haven't quite released `0.5.0` of `monai-tutorials` yet).

**Comment by bbb801** [comment]
> Hi, which tutorial is this? We use occlusion sensitivity in our [covid classification](https://github.com/Project-MONAI/tutorials/blob/master/modules/interpretability/covid_classification.ipynb) tutorial, and as far as I can tell, this is currently running successfully (see today's [cron log](https://github.com/Project-MONAI/MONAI/runs/2359076260?check_suite_focus=true#step:6:581)).
> 
> Could you try running the notebook as-is, without any modifications? You'll also need to make sure that you're using a verion of `monai` and `monai-tutorials` that are from the same time. E.g., you could use `0.4.0` for both, or `0.5.0` of `monai` and `master` of `monai-tutorials` (since we haven't quite released `0.5.0` of `monai-tutorials` yet).

Dear Dr Richard Brown,

Thank you for your prompt reply. I am sorry. It is not from the tutorial and maybe I should ask the question here. But the problem is pasted on MONAI official documentation (see: https://docs.monai.io/en/latest/visualize.html?highlight=OcclusionSensitivity)

It is here:    It is for the use of 3d OcclusionSensitivity.
![image](https://user-images.githubusercontent.com/52306405/115015726-b027d800-9ee6-11eb-9a0e-ea3376440768.png)

I ran the code and used the correct version of Monai (0.5.0). I did not revise anything but got an error. I ran:

# densenet 3d
import torch
from monai.networks.nets import DenseNet
from monai.visualize import OcclusionSensitivity

model_3d = DenseNet(spatial_dims=3, in_channels=1, out_channels=3, init_features=2, growth_rate=2, block_config=(6,))
occ_sens = OcclusionSensitivity(nn_module=model_3d, n_batch=10, stride=2)
occ_map, most_probable_class = occ_sens(torch.rand(1, 1, 6, 6, 6),  b_box=[-1, -1, 2, 3, -1, -1, -1, -1])

See the following figure:
![image](https://user-images.githubusercontent.com/52306405/115015960-06951680-9ee7-11eb-9692-10cd47334e17.png)


I have read your covid classification tutorial. It is very good. Do you have any tutorials aimed at 3d visualization using 
OcclusionSensitivity or CAM? I am looking for your tutorials and cannot find them.  Thank you.
