### ISSUE TITLE
Enhance maisi notebooks with visualization

### ISSUE THREAD

**Issue by KumoLiu** [Project-MONAI/tutorials#1855]
- After running inference in the **maisi_diff_unet_training_tutorial.ipynb** notebook, the resulting nii.gz file is saved to disk but not displayed within the Jupyter Notebook. We suggest displaying the generated 3D image in at least three views (x, y, z).

- Similarly, when performing inference in the **maisi_train_controlnet_tutorial.ipynb** notebook, the resulting nii.gz file is saved but the generated 3D image is not displayed within the Jupyter Notebook.

**Comment by dongyang0122** [comment]
The training tutorial uses synthetic data and simplified parameters to effectively demonstrate the entire process. However, it is important to note that the model will not be fully trained and may produce results resembling noise. We provide guidance on saving these results locally, enabling users to monitor the training progress as needed. Given this context, visualizing the “noise” in three different views within the tutorial notebook is not necessary.

**Comment by KumoLiu** [comment]
> The training tutorial uses synthetic data and simplified parameters to effectively demonstrate the entire process. However, it is important to note that the model will not be fully trained and may produce results resembling noise. 

Oh yes, I forgot that, make sense to me. Thanks for quick reply.
