### ISSUE TITLE
Suggested order of tutorials

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#2]
I (and so maybe other new users) would find it really useful if there was a suggested order to some of the tutorials, building in complexity, rather than just alphabetical order.

**Comment by wyli** [comment]
agreed, pytorch tutorials use these categories
![Screenshot 2020-08-25 at 12 37 15](https://user-images.githubusercontent.com/831580/91169750-c242d500-e6cf-11ea-89f4-4aff235cabb5.png)

**Comment by rijobro** [comment]
As well as categories, it might be a good idea to start with e.g., `nifti_read_example.ipynb` and `3d_image_transforms.ipynb` to get a feel for some building blocks before moving into whole networks.

**Comment by wyli** [comment]
the codebase is now restructured, I'm closing this ticket, please open new ones for further issues
