### ISSUE TITLE
show the dicom loading usage

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#21]
would be great to extend the https://github.com/Project-MONAI/Tutorials/blob/master/load_medical_images.ipynb to load DICOM

see also https://github.com/Project-MONAI/MONAI/issues/1032

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Will save synthetic data into DICOM format and read it by LoadImage.
But we need to solve below 3 issues of ITK first:
1. All ImageReaders can't support multi-threads, PR under review.
2. ITK itself can't support multi-threads, submitted issue to ITK repo, waiting for solution.
3. ITK image orientation and shape is not aligned with our existing data, using `C_order` is wrong as @ericspod raised issue.

Thanks.

**Comment by Nic-Ma** [comment]
Close as we merged the PR.
Thanks.
