### ISSUE TITLE
dynunet_pipeline - Error in Finetuning, Validation and Inference (no pretrained checkpoint)

### ISSUE THREAD

**Issue by asmakaus** [Project-MONAI/tutorials#225]
After running the successful training, I tried to run the fine-tuning, validation and inference command as guided in "tutorials/modules/dynunet_pipeline/commands". When I checked the saving folder, **runs_02_fold0_baseline** is saved properly with data folder and **data.pkl** but still the inference code is unable to read the checkpoint. Therefore, that the trained network is not loaded properly for inference. Output of inference command is shown below for reference. 

````
MONAI version: 0.5.3
Numpy version: 1.20.3
Pytorch version: 1.8.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: d78c669c67e38ddfbe572f6a0438e9df0b8c65d7

Optional dependencies:
Pytorch Ignite version: 0.4.4
Nibabel version: 3.2.1
scikit-image version: 0.18.1
Pillow version: 8.2.0
Tensorboard version: 2.5.0
gdown version: 3.13.0
TorchVision version: 0.9.1+cu102
ITK version: 5.1.2
tqdm version: 4.61.0
lmdb version: 1.2.1
psutil version: 5.8.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Loading dataset: 100%|████████████████████████████| 4/4 [00:01<00:00,  3.04it/s]
**no pretrained checkpoint**
{'val_mean_dice': 9.35896096052602e-05}`
.............................................

```

**Comment by Nic-Ma** [comment]
Hi @asmakaus ,

Thanks for your interest here.
Have you specified the checkpoint path when running the inference example?
https://github.com/Project-MONAI/tutorials/blob/master/modules/dynunet_pipeline/inference.py#L170
@yiheng-wang-nv could you please help fix it if there is really a bug?

Thanks in advance.

**Comment by asmakaus** [comment]
Thank you so much for your response. It worked now. Actually the variable **weight=model.pt** given in commands was confusing. I feel it would be better if help is provided in comments explaining it as complete directory path. 

Thanks again.

**Comment by Nic-Ma** [comment]
@yiheng-wang-nv , could you please help update the tutorial based on the feedback?

Thanks.

**Comment by yiheng-wang-nv** [comment]
> @yiheng-wang-nv , could you please help update the tutorial based on the feedback?
> 
> Thanks.

Hi @Nic-Ma and @asmakaus , actually the script has the corresponding comments, like here:
https://github.com/Project-MONAI/tutorials/blob/master/modules/dynunet_pipeline/commands/task01/finetune_multi_gpu.sh#L2
