### ISSUE TITLE
A tutorial to show the metrics API usage

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#233]
**Is your feature request related to a problem? Please describe.**
would be great to have a standalone demo/tutorial on the metrics APIs

part of https://github.com/Project-MONAI/MONAI/issues/497, followup of https://github.com/Project-MONAI/MONAI/pull/2314

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for putting this ticket.
I am thinking about the content of tutorial example today, plan to mainly introduce 2 parts:
1. How to use metrics in a regular validation program during training.
2. How to compute metrics based on saved predictions and labels, with multi-processing.

Do you have any other suggestions?

Thanks.

**Comment by wyli** [comment]
sure, it should also have a section to generate a final metric summary report

**Comment by Nic-Ma** [comment]
Sounds good!

Thanks.
