### ISSUE TITLE
Update all the examples & notebooks to use new APIs

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/tutorials#245]
The feature comes from: https://github.com/Project-MONAI/MONAI/issues/2402

**Comment by wyli** [comment]
For reference, most of the errors in this log are relevant https://github.com/Project-MONAI/MONAI/runs/2959519650?check_suite_focus=true

**Comment by wyli** [comment]
I think we should list and track all the demo/examples to be updated here, and then have multiple pull requests to address them. In this way we can review part of them while the others are getting updated.

**Comment by yiheng-wang-nv** [comment]
> I think we should list and track all the demo/examples to be updated here, and then have multiple pull requests to address them. In this way we can review part of them while the others are getting updated.

Hi @wyli , thanks for the suggestion, and I just listed them in #246 .
