### ISSUE TITLE
Multi-class segmentation

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#247]
We get quite a few questions about multi-class segmentation (e.g., https://github.com/Project-MONAI/MONAI/discussions/2302), so it would be good to have a tutorial demonstrating this workflow.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

I think this Brats tutorial is: https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/brats_segmentation_3d.ipynb.

Thanks.

**Comment by rijobro** [comment]
oh great, thanks!
