### ISSUE TITLE
Change `ToTensor` to `EnsureType` in all examples and tutorials

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/tutorials#259]
**Is your feature request related to a problem? Please describe.**

Hi @wyli @rijobro @ericspod ,

Do you guys think we should change all the `ToTensor` transform in the tutorials and examples to `EnsureType` transform based on our previous discussion?
If yes, @yiheng-wang-nv will update all in the PR.

Thanks.

**Comment by ericspod** [comment]
That's the new API we want to encourage people to use so I'd say we should. We've left `ToTensor` and `ToNumpy` in but these will likely disappear eventually as they're redundant now.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help update all the `ToTensor` to `EnsureType` directly?
@wyli @rijobro do you guys have any other comments?

Thanks.
