### ISSUE TITLE
tensor instead of list in BraTS segmentation tutorial

### ISSUE THREAD

**Issue by talhaanwarch** [Project-MONAI/tutorials#269]
In brats tutorial, the list is passed to Dice metric, is not it should be tensor?

```
self.criterion=DiceLoss(to_onehot_y=False, sigmoid=True, squared_pred=False)
self.dice_metric=DiceMetric(include_background=True, reduction="mean")
```
```
val_outputs = [post_trans(i) for i in decollate_batch(val_outputs)]
self.dice_metric(y_pred=val_outputs, y=val_labels)
```

Because when I do this, it says sigmoid need tensor input instead of a list
`TypeError: sigmoid(): argument 'input' (position 1) must be Tensor, not list`

**Comment by Nic-Ma** [comment]
Hi @talhaanwarch ,

Thanks for your interest and experiment here.
All the MONAI metrics in **v0.6** can support a list of tensors as input.
I am afraid you are using MONAI v0.5 or using the `DiceLoss` instead of `DiceMetric`?

Thanks.
