### ISSUE TITLE
Tutorial Request for Validation on Original Image Spacing

### ISSUE THREAD

**Issue by dongyang0122** [Project-MONAI/tutorials#279]
To achieve the full pipeline, it is better to have a complete tutorial for model training, validation, inference on original spacing (and optional validation on the original spacing). And it would be helpful to add contents in the following tutorial.

https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d.ipynb

Thanks! @yiheng-wang-nv

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , @Nic-Ma , @rijobro , should I add a new notebook, or update `spleen_segmentation_3d.ipynb` directly?

**Comment by rijobro** [comment]
I'm not sure that inference using the original spacing is a good idea. If you've trained your network with certain sized voxels, you'll want to infer with those size voxels, too. Do you mean performing the inference on the under-sampled images, and then using the inverse transforms to resample them back to the original spacing?

**Comment by dongyang0122** [comment]
There is a good example of reversing the model output back to the original spacing. It would be helpful to further calculate the validation accuracy of the original spacing data. Because this will be a fair way to compare models trained at different image spacings. Moreover, it is better to combine the solutions into a complete tutorial rather than fragments (at least for one task). Thank you! @rijobro
