### ISSUE TITLE
How to choose spacing in dynunet

### ISSUE THREAD

**Issue by RespectKnowledge** [Project-MONAI/tutorials#298]
Hello 
I want to use dynunet for segmentation. I have dataset with different spacing. How can I choose spacing for my own dataset?

**Comment by Nic-Ma** [comment]
Hi @RespectKnowledge ,

Thanks for your interest here.
@wyli @rijobro , could you please help share some experience about `spacing` values?

Thanks in advance.

**Comment by wyli** [comment]
New utility function is now available https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/dataset_summary.py for computing median spacing from a dataset.

**Comment by RespectKnowledge** [comment]
Thanks for sharing
