### ISSUE TITLE
Colab links point to main respository

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/Tutorials#3]
Tutorials have a link for opening them with Colab:
![image](https://user-images.githubusercontent.com/33289025/91020943-686cdd00-e5f3-11ea-8e7c-9133311713c7.png)

But this points to their location prior to being moved into a separate repository:
![image](https://user-images.githubusercontent.com/33289025/91020663-090ecd00-e5f3-11ea-9816-db0c243ba3f3.png)

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/Tutorials/pull/11
