### ISSUE TITLE
torch.jit.load() cannot load downloaded deepgrow models

### ISSUE THREAD

**Issue by yongyuandeyezi** [Project-MONAI/tutorials#306]
I tried to run the inference of deepgrow, it crashed when loaded the  downloaded model.
model = jit.load(model_path)
Segmentation fault (core dumped)

**Comment by Nic-Ma** [comment]
Hi @SachidanandAlle ,

Could you please help confirm this issue? Maybe we need to update the DeepGrow tutorial?

Thanks in advance.

**Comment by SachidanandAlle** [comment]
What is the downloaded model size here.. may be the download is not complete.. what is the download url..?

**Comment by yongyuandeyezi** [comment]
> What is the downloaded model size here.. may be the download is not complete.. what is the download url..? And what gpu do you have?
download url of deepgrow 2d: https://drive.google.com/uc?id=1_J4qj-JRqQc9g8SGegq63Z_wq6gqgLLg
download url of deepgrow 3d: https://drive.google.com/uc?id=1BcU4Z-wdkw7xjydDNd28iVBUVDJYKqCO
deepgrow_2d.ts: 30517kb
deepgrow_3d.ts: 88499kb
I can run the inference using the model 2d_model.ts trained by myself
![image](https://user-images.githubusercontent.com/35683606/129124663-b2b6e917-7098-455e-bfe0-27eda8ccfb9b.png)
