### ISSUE TITLE
Add tutorial example using NiftiSaver

### ISSUE THREAD

**Issue by dyollb** [Project-MONAI/tutorials#311]
**Is your feature request related to a problem? Please describe.**
I am using the spleen lighting tutorial with custom data and would like to save the predicted segmentations as nifti files. Since the NiftiSaver and PngSaver are not used in the examples it is a bit difficult to figure out how to use them.

**Describe the solution you'd like**
Please add an example how to use `NiftiSaver`.

**Describe alternatives you've considered**

**Additional context**
My current code looks like this:
```
    test_ds = CacheDataset(
        data=[{"image": f} for f in test_files],
        transform=net.predicition_transforms(),
        cache_rate=1.0,
        num_workers=0,
    )
        
    test_loader = torch.utils.data.DataLoader(
        test_ds, batch_size=1, num_workers=0
    )

    os.makedirs(output_dir, exist_ok=True)
    saver = NiftiSaver(output_dir=output_dir, separate_folder=False, resample=False)
    with torch.no_grad():
        for i, test_data in enumerate(test_loader):
            roi_size = (160, 160, 160)
            sw_batch_size = 4
            test_outputs = sliding_window_inference(
                test_data["image"].to(device), roi_size, sw_batch_size, net
            )

            pred_labels = test_outputs.argmax(dim=1, keepdim=True)
            saver.save_batch(pred_labels, test_data["image_meta_dict"])

while the dimension seems correct, and I can more or less recognize the pattern in the segmentation, the labels seem incorrect (very different to slice view displayed with matplotlib, examples of both attached).
```
![slice_NiftiSaver](https://user-images.githubusercontent.com/12702862/129580768-faaad5f3-577a-45e4-84d3-778683d7d7bc.PNG)
![drcmr05_case1](https://user-images.githubusercontent.com/12702862/129580997-c666e645-ce90-4f85-9014-a3c1e9df1042.png)

**Comment by Nic-Ma** [comment]
Hi @dyollb ,

Thanks for your interest here and experiments.
I think you can refer to this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_evaluation_dict.py#L64

Thanks.

**Comment by dyollb** [comment]
> Hi @dyollb ,
> 
> Thanks for your interest here and experiments.
> I think you can refer to this example:
> https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_evaluation_dict.py#L64
> 
> Thanks.

Thanks for your reply. The approach using SaveImage from your link above produces the same weird image.

It seems I have a bug somewhere else, maybe related to loading/saving the trained model. Closing this issue.
