### ISSUE TITLE
How to segment spleen of test image without mask?

### ISSUE THREAD

**Issue by Shyamapada34** [Project-MONAI/tutorials#328]
Hi Monai Team, 
I have trained segmentation model using your code 'spleen_segmentation_3d.ipynb' by using MSD spleen dataset. I have a new spleen dataset, where mask is absent. How to inference these test images ?

with regards
Shyama

**Comment by Nic-Ma** [comment]
Hi @Shyamapada34 ,

Thanks for your interest here.
I think you can refer to this tutorial example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/torch/unet_inference_dict.py

Thanks.

**Comment by Shyamapada34** [comment]
Thanks for immediate reply.  
I have another question. I want to segment pancreas and pancreatic cancer. Can you suggest which is the best model in your repo for pancreas CT data?
with regards
Shyama

**Comment by Nic-Ma** [comment]
Sorry I don't have experience on that dataset. Maybe you can start investigation from UNet.

Thanks.

**Comment by Shyamapada34** [comment]
Thanks for your reply

with regards
Shyama
