### ISSUE TITLE
Error when using batch size > 1 in the spleen segmentation example

### ISSUE THREAD

**Issue by sergiosgatidis** [Project-MONAI/tutorials#343]
**Describe the bug**

When following the 3D Spleen segmentation example I get the following error when changing the batch size from 1 to 2:

"RuntimeError: stack expects each tensor to be equal size, but got [1, 226, 157, 113] at entry 0 and [1, 305, 267, 124] at entry 1
Collate error on the key 'image' of dictionary data.

MONAI hint: if your transforms intentionally create images of different shapes, creating your `DataLoader` with `collate_fn=pad_list_data_collate` might solve this problem (check its documentation)."

It seems like the whole CT datasets (not only the extracted patches) are stacked which results in this error when matrix sizes are different. I encountered this issue also with other datasets but could not find a workaround.

**To Reproduce**

I used Colab with the settings provided in the example script in order to exclude any local version issues etc.

**Expected behavior**

I would expect the batches to be built from the extracted patches; this should not require stacking of the whole image datasets.

**Comment by cherishleon** [comment]
May I know that you've solved the problem?
