### ISSUE TITLE
Tensor in cuda to numpy

### ISSUE THREAD

**Issue by Sebagam** [Project-MONAI/tutorials#347]
Hi all,

I have the following tensor which is the probability output of my MONAI Densenet model:

[tensor([0.0507, 0.9493], device='cuda:0'),
 tensor([0.0484, 0.9516], device='cuda:0'),
 tensor([0.0021, 0.9979], device='cuda:0'),...

I want to transform it to NumPy, but I don't have the traditional methods such as .numpy() or .cpu()

How can I do this?
Thanks

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

The `ToNumpy` transform may help you:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/utility/array.py#L377

Thanks.

**Comment by Sebagam** [comment]
Thanks, do you mean something like:

y_probs = Compose([EnsureType(),ToTensor()])
y_probs(y_pred_act)

the tensor "y_pred_act" still is in tensor form after that transformation

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

I mean to use `ToNumpy` transform not `ToTensor` transform.

Thanks.

**Comment by Sebagam** [comment]
Sorry is too early here : )
