### ISSUE TITLE
3D classification tutorial - Occlusion sensitivity

### ISSUE THREAD

**Issue by Sebagam** [Project-MONAI/tutorials#351]
Dear all,

Why is the occlusion sensitivity output vertically inverted in the tutorial? How can you rotate the plot?
In my case, I'm getting a 90 degrees rotated output.

Best

**Comment by Nic-Ma** [comment]
Hi @Sebagam ,

Thanks for your feedback, may I know which exact tutorial you refer to?

**Comment by Sebagam** [comment]
This one:
https://github.com/Project-MONAI/tutorials/blob/master/3d_classification/densenet_training_array.ipynb

**Comment by Nic-Ma** [comment]
I think we didn't apply `Orientation` transform in this example, maybe you can add it to correct the image orientation?
CC @wyli @ericspod .

Thanks.

**Comment by wyli** [comment]
will the `origin{'upper', 'lower'},` parameter of the imshow resolve this? 
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.imshow.html
