### ISSUE TITLE
Vit tutorial

### ISSUE THREAD

**Issue by yimuu** [Project-MONAI/tutorials#355]
Can you provide a tutorial on using Vit?

**Comment by ahatamiz** [comment]
Hi @yimuu 

Thanks for your suggestion. Sure, I will create a PR to address this. It may take some time but will be added soon.

**Comment by jhkang0526** [comment]
Do you have an approximate release date for the tutorial on using ViT??

I'm going to use this to proceed, but there's an error, so I'd like to refer to it.

**Comment by ahatamiz** [comment]
Hi @jhkang0526 

Thanks for your interest. We still don't have an ETA for ViT tutorial. But in the meantime, please feel free to let me know what error you face so we can help. 

Thanks
