### ISSUE TITLE
nvflare tutorial relies on monai 0.6.0.

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#365]
"num_class" brings an error for nvflare tutorial since it relies on monai 0.6.0.

__Originally posted by @yiheng-wang-nv in https://github.com/Project-MONAI/tutorials/pull/322#issuecomment-924692263__

**Comment by yiheng-wang-nv** [comment]
Thanks @wyli , since @holgerroth suggests to add deterministic flag in the nvflare tutorial, I will submit a pr to cover these two places together.

**Comment by yiheng-wang-nv** [comment]
Hi @holgerroth , so far, nvflare cannot ensure determinism (I tested with clara and monai based trainer). I will update the tutorial with monai 0.7.0 first.
