### ISSUE TITLE
Rand3dElasticd example is blank

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#378]
Example of Rand3dElasticd is blank in [this](https://github.com/Project-MONAI/tutorials/blob/master/modules/3d_image_transforms.ipynb) tutorial (bottom of notebook).

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I think that's random transform, could you please help re-run the notebook to show a more `reasonable` result in the chart?

Thanks.

**Comment by rijobro** [comment]
Thanks. That said, even though it's a random transform, it should be possible to set the parameters such that the image always stays in the field of view.

**Comment by Nic-Ma** [comment]
That makes sense, we should set random seed in it.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

I submitted PR #383 to update the tutorial with a fixed random state.
Could you please help review it?

Thanks.
