### ISSUE TITLE
Slightly revise 2D segmentation tutorial scripts 

### ISSUE THREAD

**Issue by hw-ju** [Project-MONAI/tutorials#380]
For tutorial scripts here https://github.com/Project-MONAI/tutorials/tree/master/2d_segmentation/torch,
the synthetic PNG images are always whole black, since the image arrays are made up of 0s and 1s. One user, who just begins to learn MONAI, found it quite confusing and asked me if anything is wrong. 

Shall we slightly modify these scripts so that the synthetic images are not whole black and are saved in a non-temporary directory, so that it's easier for beginners to check if everything runs fine?

**Comment by Nic-Ma** [comment]
Hi @hw-ju ,

Thanks for your feedback, makes sense to me.
I will try to enahcne the tutorial example ASAP.

Thanks.
