### ISSUE TITLE
SLURM + Singularity sample scripts

### ISSUE THREAD

**Issue by hw-ju** [Project-MONAI/tutorials#381]
The Research Computing team at University of Florida just put sample scripts for multi-node multi-gpu MONAI using SLURM and Singularity at their github https://github.com/UFResearchComputing/MultiNode_MONAI_example. 

Shall we put a link in MONAI tutorial repo to direct users there? The scripts contain comments and should be self-explanatory.

**Comment by Nic-Ma** [comment]
Hi @hw-ju ,

Thanks for providing the reference link, I will put it in the distributed training guide of MONAI tutorial.
