### ISSUE TITLE
Problem with 3d_segmentation/brats_segmentation_3d.ipynb

### ISSUE THREAD

**Issue by Ryurin** [Project-MONAI/tutorials#392]
Hello, 

I tried this tutorial, but I don't have the waited result. I obtained a binary segmentation, whereas the title suggests multi label segmentation. 

The label images have 4 labels (0 to 3) and if I comment ConvertToMultiChannelBasedOnBratsClassesd class, I have a multi label image (but the model cannot be created). If I display label image with this correction function, I obtain just two color (purple and yellow), but the example have three color (purple, yellow and green). 

So I don't understand my mistake. What is the result of this tutorial ? And if it's multi label (et and I need it), where is the mistake ? 

Thank you for your reading !

**Comment by Ryurin** [comment]
Sure, you can see my result below. And thanks for your answer, I was scared to misunterstand the goal of this tutorial.

image shape: torch.Size([4, 240, 240, 155])
label shape: torch.Size([3, 240, 240, 155])

![output](https://user-images.githubusercontent.com/15381434/136379071-2aa75960-af95-41a6-9bf0-cf06bc634c93.png)

**Comment by Nic-Ma** [comment]
No problem.
Please feel free to raise a discussion or issue if you have any more questions.

Thanks.
