### ISSUE TITLE
Code with new performance enhancements - CUDA out of memory error

### ISSUE THREAD

**Issue by hasansari** [Project-MONAI/tutorials#401]
I am trying the new performance enhancements following the updated tutorial on spleen segmentation but I am getting "CUDA out of memory error" when I try the example with performance enhancements. The old code without the performance enhancements works fine. I am keeping the patch size, batch size, number of samples same or smaller values. 

Any ideas what might be causing this?

**Comment by Nic-Ma** [comment]
Hi @hasansari ,

Thanks for your interest here.
The fast training solution caches data to GPU memory directly, so in theory, it requires a bigger memory size.

Thanks.
