### ISSUE TITLE
Need to retrain the AMP tutorial

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/tutorials#418]
**Is your feature request related to a problem? Please describe.**
As the chart in the AMP tutorial is more 1 year ago, Daguang and Prerna requested to retrain the tutorial notebook with latest docker and code. And add the exact test values in the charts.

**Comment by wyli** [comment]
has this been done @Nic-Ma?

**Comment by Nic-Ma** [comment]
I think so, current tutorial was executed with `Pytorch version: 1.9.0a0+c3d40fd`.

Thanks.
