### ISSUE TITLE
Please add another interpolation mode for NiftiSaver to avoid zigzag pattern caused by bilinear interpolation.

### ISSUE THREAD

**Issue by Jingnan-Jia** [Project-MONAI/tutorials#440]
**Sorry I should propose this issue in MONAI main branch, instead of its tutorial. Please help to delete this issue because I have already proposed the same issue [here](https://github.com/Project-MONAI/MONAI/issues/3333)**

**Is your feature request related to a problem? Please describe.**
In the current NiftiSaver, there are only two interpolation modes:  "nereast" and "bilinear". It is not enough. Detailed explanication as follows.

If I have an lung CT image with shape (1024, 512, 512). To do lung or lobe segmentation, I need to down sample the original CT image to a smaller size (256, 256, 256). So the resample factors are (0.25, 0.5, 0.5). After I finish the model training, the predicted lung or lobe segmentation needs to be up-sampled to the original shape during inference. If I use "bilinear" mode for NiftiSaver, **some zigzag pattern would appear along the edge of lung or lobe**.

**Describe the solution you'd like**
Using current MONAI, I came up with several possible solutions  to avoid the zigzag pattern in NiftiSaver :

1. Use "bilinear" mode in NiftiSaver at first, and then use a threshold of 0.5 to binarize the results. However this method only applies to binary segmentation tasks, like lung segmentation. In multi-label segmentation, there is not a proper threshold for the whole image.
2. I can use "nearest" mode at first to get the output with zigzag pattern. Then use some smooth algorithms to remove the zigzag pattern.

I do not have a satisfied solution in current MONAI. I hope NiftiSaver can have a mode "bilinear2nearest". In this mode, the NiftiSaver will:

```
# In a n-label image segmentation
1. apply `argmax` to prediction, get the discreted masks.
2. apply `on_hot_encode` to the discreted masks, to get `n` channels of binary masks.
3. apply `bilinear` interpolation mode to eac channel of binary mask, get `n` channels of masks of original size.
4. apply `threshold=0.5` to all channels, get `n` channels of binary masks.
5. apply `on_hot_decode` to get the final n-label mask.
```

I have implementated this workflow in my own code, and it works well. I hope MONAI can also add this feature to NiftiSaver. 

**Note**: The zigzag pattern matters especially when the interpolation factor is far from 1.

**Comment by wyli** [comment]
closing in favour of https://github.com/Project-MONAI/MONAI/issues/3333
