### ISSUE TITLE
3d classification no data download

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#45]
**Describe the bug**
All 3D classification tutorials assume that the data is in `'workspace/data/medical/ixi/IXI-T1/`, but none do the download.

**To Reproduce**
1. Load any 3D classification tutorial and run.

**Expected behavior**
Tutorial should be able to run the whole way through without user intervention.

**Environment (please complete the following information):**
N/A

**Comment by Nic-Ma** [comment]
Hi @rijobro ,

If you run from https://github.com/Project-MONAI/tutorials/blob/master/runexamples.sh, it will download data first.
Thanks.

**Comment by rijobro** [comment]
Ok thanks. Is this mentioned somewhere? I guess it should be in the `README`.
