### ISSUE TITLE
tutorials are broken due to `AsDiscrete` and `AsDiscreteD` updates

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#450]
**Describe the bug**
the recent update of `AsDiscrete` and `AsDiscreteD` break many tutorials,
this should be rectified accordingly 

see also https://github.com/Project-MONAI/MONAI/pull/3352.

**Comment by wyli** [comment]
@yiheng-wang-nv, could you please look into this?

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , sure. I was busy on other tasks, and now I'm able to start to update the related tutorials.
