### ISSUE TITLE
Performance_profilling error

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/tutorials#453]
I met the following error when running `radiology/train_base_nvtx.py`:

![Screen Shot 2021-11-23 at 9 08 53 PM](https://user-images.githubusercontent.com/68361391/143031843-4dbc1f5a-11d3-428d-88db-c87d24fcc0a3.png)

**Comment by yiheng-wang-nv** [comment]
Hi @dongyang0122 , can you please help to check the file? I used MONAI docker (MONAI version: 0.8.0rc1+5.g37930a9b) and installed the libraries in `requirements.txt`

**Comment by dongyang0122** [comment]
@drbeh Hi Behrooz, can you take a look of this error message? Thanks!

**Comment by wyli** [comment]
closing in favor of #628
