### ISSUE TITLE
Loading of pretrained weights of the new ssl tutorial fails

### ISSUE THREAD

**Issue by elitap** [Project-MONAI/tutorials#461]
**Describe the bug**
The loading of the pretrained ViT weight ins tutorials/self_supervised_pretraining/ssl_finetuning_train.py fails with:
Unexpected key(s) in state_dict: "linear_1.weight", "linear_1.bias". 

**To Reproduce**
Download the provided weight file from: https://drive.google.com/file/d/1z0BouIiQ9oLizubOIH9Rlpad5Kk_2RtY/view
running ssl_finetuning_train.py

**Expected behavior**
should load the weights

**Environment (please complete the following information):**
MONAI version: 0.8.0
Pytorch version: 1.9.1+cu111

**Additional context**
Thank you for the awsome tutorial, hope to get the pretrained weights running to save some time :-)

**Comment by Nic-Ma** [comment]
Thanks for the feedback!
Hi @finalelement , could you please help confirm the issue?

Thanks in advance.

**Comment by finalelement** [comment]
@Nic-Ma , @elitap Thank you for highlighting this issue, let me double check and get back.

**Comment by finalelement** [comment]
Fix being pushed via https://github.com/Project-MONAI/tutorials/pull/465

**Comment by elitap** [comment]
Thank you very much, all weights are loaded perfectly now. Getting them saved me a lot of compute. Really nice tutorial thanks you :-)
