### ISSUE TITLE
AsDiscrete is expecting num_classes to be int but in documentation says num_classes is deprecated 

### ISSUE THREAD

**Issue by praveenck06** [Project-MONAI/tutorials#462]
**Describe the bug**
AsDiscrete is expecting num_classes to be int but in documentation says num_classes is deprecated 

For post transforms 
`post_pred = Compose([EnsureType(), AsDiscrete(argmax=True, to_onehot=2,)])
post_label = Compose([EnsureType(), AsDiscrete(to_onehot=2,  )])
`

**Screenshots**
![image](https://user-images.githubusercontent.com/33887466/143839052-f2fb0df4-ca64-4a5d-99e8-db1851349405.png)

if I provide num_classes then its working as expected

`post_pred = Compose([EnsureType(), AsDiscrete(argmax=True, to_onehot=2, num_classes=2)])
post_label = Compose([EnsureType(), AsDiscrete(to_onehot=2,  num_classes=2)])`

**Environment (please complete the following information):**
 - Python version 3.8
 - MONAI version 0.7.0

**Comment by Nic-Ma** [comment]
Hi @praveenck06 ,

Thanks for your interest here.
`num_classes` was just deprecated in MONAI v0.8, I see you are using MONAI v0.7.
So maybe you can update your MONAI version and try again?

Thanks.

**Comment by praveenck06** [comment]
My fault, I didnt notice 0.8 was released.  
After updating to MONAI v0.8 I am not getting error 

Thanks @Nic-Ma 

Also, thanks for this amazing library and tutorials

**Comment by Nic-Ma** [comment]
Please feel free to raise a ticket if you feel any other issues.

Thanks.
