### ISSUE TITLE
3d_segmentation/brats_segmentation_3d.ipynb TypeError: got an unexpected keyword argument 'threshold' for AsDiscrete transform

### ISSUE THREAD

**Issue by sebastianffx** [Project-MONAI/tutorials#463]
**Describe the bug**
The argument _threshold_ is not expected when calling the transform _AsDiscrete_ cell 8 in the tutorial.

**To Reproduce**
1. Go to 3d_segmentation/brats_segmentation_3d.ipynb
2. Run code cells up to the number 8, the bug should come up.

 
**Expected behavior**
That the transformation could work with the specified threshold, probably is just a matter of renaming the argument to logit_thresh?

**Screenshots**
<img width="1121" alt="Screenshot 2021-11-29 at 14 05 22" src="https://user-images.githubusercontent.com/937885/143873215-e83949ee-a86a-4f51-83d2-b07e708ddb10.png">

**Environment (please complete the following information):**
 - OS: MacOS 12.01
 - Python version 3.9.7
 - MONAI version 0.7.0
 - CUDA/cuDNN version: (N/A) CPU
 - GPU models and configuration: (N/A)

**Comment by gvigkannan** [comment]
Hi! The updated version of Monai - 0.8.0 was able to fix this issue.
