### ISSUE TITLE
SSL random augmentations broken with 0.8.0

### ISSUE THREAD

**Issue by razorx89** [Project-MONAI/tutorials#467]
The self-supervised learning tutorial uses random augmentions to generate two different views of a CT image. However, with MONAI 0.8.0 the behaviour of the random transforms changed and the same random transform states will be applied to both image keys.

https://github.com/Project-MONAI/tutorials/blob/99e16a7d57c6d02773b510ed85cd0440cc4bba92/self_supervised_pretraining/ssl_script_train.py#L75-L82

https://github.com/Project-MONAI/MONAI/blob/ad0f866ff4e34a91ca9f59cd69e2e01bdd6c83c9/monai/transforms/intensity/dictionary.py#L1489-L1491

**Comment by finalelement** [comment]
This being fixed by [PR](https://github.com/Project-MONAI/tutorials/pull/468)
