### ISSUE TITLE
Monai tutorials wrong link

### ISSUE THREAD

**Issue by alexey-khorkin** [Project-MONAI/tutorials#491]
I just noticed that this link is not correct:
![image](https://user-images.githubusercontent.com/89856652/147019502-4f05ab36-41aa-4896-9b8d-c3ee0ee70853.png)
If we click on the link, we get:
![image](https://user-images.githubusercontent.com/89856652/147019600-34e60e94-ac8d-4862-91a8-274066ccf33d.png)

**Comment by Nic-Ma** [comment]
Hi @alexey-khorkin ,

Thanks for your issue report, let me update it ASAP.

**Comment by Nic-Ma** [comment]
Hi @alexey-khorkin ,

I have updated the link in the main page.

Thanks.
