### ISSUE TITLE
Pip installs at start of each notebook?

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#50]
Should we be pip installing `monai` and its dependencies at the start of each notebook?

Discussion continued from https://github.com/Project-MONAI/tutorials/pull/47.

My personal feeling is that we should lift all `pip install`s from our notebooks as the relevant instructions are already in our [README.md](https://github.com/Project-MONAI/tutorials/blob/master/README.md). It also saves us from having to update as our notebooks/dependencies change.

**Comment by Nic-Ma** [comment]
Hi @wyli and @ericspod ,

Should we raise a discussion about this topic in next MONAI meeting?
Thanks.

**Comment by wyli** [comment]
we've discussed this in the meeting already, the solution is to tag a branch such as v0.3.0, which will depend on `pip install monai==0.3.0`. and the master branch depends on `pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI`.

we need some CI tests to ensure the master branch works fine

**Comment by wyli** [comment]
Just pushed 0.3.0 tag https://github.com/Project-MONAI/tutorials/tree/0.3.0, 
so for the users with pip install monai==0.3.0, they should check out this link, instead of the tutorial's master branch.

**Comment by Nic-Ma** [comment]
Sounds good! Thanks @wyli

**Comment by wyli** [comment]
this makes Colab not directly runnable. so we need some instructions for colab user to manually add a  `%pip install monai`  cell
