### ISSUE TITLE
drop the check of  `monai.utils.get_torch_version_tuple() >= (1, 6)`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#509]
**Describe the bug**
because the core codebase now requires at least torch 1.6

**Comment by ericspod** [comment]
As in lines like `amp=True if monai.utils.get_torch_version_tuple() >= (1, 6) else False` where we choosing to use AMP only if available? If Pytorch 1.6 is assumed to always be used then yes we should. So far these are the only places `get_torch_version_tuple` is used.

**Comment by wyli** [comment]
Yes, it's mainly for the amp flag.

**Comment by Shadow-Devil** [comment]
I've removed the checks and created a PR for it.
