### ISSUE TITLE
RandSpatialCropSamplesd and CopyItemsd problem

### ISSUE THREAD

**Issue by 834799106** [Project-MONAI/tutorials#544]
When I compose
RandSpatialCropSamplesd(keys="image", roi_size=(128, 128, 128), random_size=False, num_samples=2,),
CopyItemsd(keys=["image"], times=1, names=["image2"], allow_missing_keys=False), it will make mistakes in CopyItemsd. My guess is that RandSpatialCropSamplesd returns the value as a list. Is there any way to solve this problem? This is code from the self-supervision tutorial

**Comment by wyli** [comment]
I couldn't replicate your issue:

```py
import numpy as np

from monai.transforms import Compose, CopyItemsd, RandSpatialCropSamplesd

xform = Compose(
    [
        RandSpatialCropSamplesd(keys="image", roi_size=(128, 128, 128), random_size=False, num_samples=2),
        CopyItemsd(keys=["image"], times=1, names=["image2"], allow_missing_keys=False),
    ]
)
output = xform({"image": np.zeros((1, 200, 200, 200))})
print(output[0]["image"].shape)
```

please create a separate issue with detailed information so that we can help here.
