### ISSUE TITLE
a demo to load a directory of DICOM as an array

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#550]
Perhaps show an example in the load medical images tutorial that it's possible to just give the containing folder. https://github.com/Project-MONAI/tutorials/blob/master/modules/load_medical_images.ipynb 

Right now it's only showing an example giving a list of files.

_Originally posted by @digernes in https://github.com/Project-MONAI/MONAI/issues/1646#issuecomment-1040100967_

**Comment by yiheng-wang-nv** [comment]
Update: I tried to update the tutorial, but met an issue:
To loading a whole directory, it seems all images from the folder should belong to the same DICOM series.
I tried to create a DICOM series via using `itk.ImageSeriesWriter`, but still failed.

Hi @wyli , here do you have any suggestion? Can we do 1) download a DICOM series (such as from: https://www.ircad.fr/fr/recherche/3d-ircadb-01-fr/) 2) show the demo during the notebook?

**Comment by wyli** [comment]
thanks I'm not sure about the licensing of the data, perhaps you can create tiny images following this script: https://simpleitk.readthedocs.io/en/master/link_DicomSeriesFromArray_docs.html?highlight=dicom
