### ISSUE TITLE
When I use dice_metric in multiple processes, the following happens when I call dice_metric.aggregate() in the main process.  

### ISSUE THREAD

**Issue by 834799106** [Project-MONAI/tutorials#564]
CUDA out of memory. Tried to allocate 6056239117.41 GiB (GPU 0; 44.56 GiB total capacity; 2.20 GiB already allocated; 40.30 GiB free; 2.54 GiB reserved in total by PyTorch). unable to sync buffer contents: [[tensor([0.0925, 0.0137, 0.0055], device='cuda:0'), tensor([0.0103, 0.0024, 0.0013], device='cuda:0'), tensor([0.0223, 0.0008, 0.0015], device='cuda:0'), tensor([0.0561, 0.0042, 0.0034], device='cuda:0'), tensor([0.0800, 0.0065, 0.0041], device='cuda:0'), tensor([0.0890, 0.0091, 0.0054], device='cuda:0'), tensor([0.0727, 0.0123, 0.0001], device='cuda:0'), tensor([0.0182, 0.0013, 0.0009], device='cuda:0'), tensor([0.0195, 0.0009, 0.0012], device='cuda:0')

**Comment by wyli** [comment]
it's difficult to debug based on this description, could you provide more information?
perhaps you can try `detach()` the relevant input tensors.
