### ISSUE TITLE
Verify tutorials with MONAI v0.8.1

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/tutorials#565]
**Is your feature request related to a problem? Please describe.**
As we already released MONAI v0.8.1, it's better to double confirm the tutorials and examples with it.
Then we can tag v0.8.1 for tutorials repo.

**Comment by yiheng-wang-nv** [comment]
Hi @Nic-Ma , I'm working on this

**Comment by yiheng-wang-nv** [comment]
Hi @drbeh , could you please help to verify the tutorials in `pathology/`?
The dataset in https://www.kaggle.com/c/prostate-cancer-grade-assessment/ is >400 GB, and my hard disk cannot take it

**Comment by drbeh** [comment]
Hi @yiheng-wang-nv, sure I will check the tutorial.
