### ISSUE TITLE
RuntimeError: index 3 is out of bounds for dimension 1 with size 2

### ISSUE THREAD

**Issue by HripsimeS** [Project-MONAI/tutorials#578]
Hello. I am trying to optimize the following notebook of 3D Unet segmentation on my dataset (3D images CT images with their labels).  https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d.ipynb

But unfortunately I am getting an error after execution of PyTorch training process part. It seems that the running is having an error on loss_function calculation and eventually I received a "RuntimeError: index 3 is out of bounds for dimension 1 with size 2".
This is my code, in case if that could be helpful: https://colab.research.google.com/drive/1cQqW54eBGuoWJHG1lRYOrnjYKZUbzBfs#scrollTo=40e3768c

Do you have any ideas what is going on and how to fix this error? Thanks a lot in advance!

**Comment by yiheng-wang-nv** [comment]
Hi @HripsimeS , login to colab is not very convenient on my side, could you provide the code in other place, like pushed into your forked repo? Thanks!

**Comment by HripsimeS** [comment]
@yiheng-wang-nv thanks a lot for your quick reply. Please find below a github link to my notebook:
https://github.com/HripsimeS/Computer-Vision/blob/main/3DUnet_CTPelvic1K.ipynb

I tried to run the training on both CPU and CUDA, in both cases I got exactly the same description of error line by line. Just the finial sentence is different.

For the running on CPU 
RuntimeError: index 3 is out of bounds for dimension 1 with size 2

For the running on GPU
RuntimeError: CUDA error: device-side assert triggered

Please let me know if you need additional information. Look forward to hearing from you!

**Comment by yiheng-wang-nv** [comment]
Hi @HripsimeS , it seems there are some value(s) = 3 in your `labels`, and since you set `out_channels=2`, do one hot encoding before calculating the loss will raise this error.
Can you confirm that the number of classes is correct, and the values in your labels are correct?

**Comment by HripsimeS** [comment]
@yiheng-wang-nv thanks for your reply! The number of classes are 4 and the values in my labels are (0,1,2,3). 
I need to write to_onehot=4 and out_channels=4 as well? How about in_channels, how much it should be in my case? 
Look forward to hearing from you!

**Comment by yiheng-wang-nv** [comment]
Hi @HripsimeS , 
> I need to write to_onehot=4 and out_channels=4 as well?
Yes, your settings for `post_pred` and `post_label` are correct, but `out_channels ` for `model` should be changed into 4.
The value of `in_channels` depends on your input channel size, I think 1 is correct otherwise you will meet the error before calculating the loss step.

**Comment by HripsimeS** [comment]
@yiheng-wang-nv thanks a lot, it is working now! 👍
