### ISSUE TITLE
RuntimeError: index 3 is out of bounds for dimension 1 with size 2

### ISSUE THREAD

**Issue by HripsimeS** [Project-MONAI/tutorials#579]
@yiheng-wang-nv I am trying to optimize the following notebook of 3D Unet segmentation on my dataset (3D images CT images with their labels). https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/spleen_segmentation_3d.ipynb

Here is a link for my notebook:
https://github.com/HripsimeS/Computer-Vision/blob/main/3DUnet_CTPelvic1K.ipynb

I tried to run the training on both CPU and CUDA, in both cases I got exactly the same description of error line by line. Just the finial sentence is different.

For the running on CPU
RuntimeError: index 3 is out of bounds for dimension 1 with size 2

For the running on GPU
RuntimeError: CUDA error: device-side assert triggered

Do you have any ideas what is going on and how to fix this error? Thanks a lot in advance!

**Comment by yiheng-wang-nv** [comment]
Hi @HripsimeS , this ticket is duplicate thus can we discuss within #578 ? Let me close this ticket.
