### ISSUE TITLE
 cannot import name 'SupportsIndex'

### ISSUE THREAD

**Issue by Ouyuxuan623** [Project-MONAI/tutorials#584]
When I "import catalyst.dl"
It says :---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-557031f18a64> in <module>
----> 1 import catalyst.dl

~/.local/lib/python3.6/site-packages/catalyst/dl/__init__.py in <module>
      1 # flake8: noqa
      2 
----> 3 from catalyst.core import *
      4 
      5 from .callbacks import *

~/.local/lib/python3.6/site-packages/catalyst/core/__init__.py in <module>
      7 
      8 from .experiment import IExperiment
----> 9 from .runner import IRunner, IStageBasedRunner
     10 from .callback import (
     11     Callback,

~/.local/lib/python3.6/site-packages/catalyst/core/runner.py in <module>
     10 from torch.utils.data import DataLoader, DistributedSampler
     11 
---> 12 from catalyst.core import utils
     13 from catalyst.core.callback import Callback, CallbackScope
     14 from catalyst.core.experiment import IExperiment

~/.local/lib/python3.6/site-packages/catalyst/core/utils/__init__.py in <module>
      2 
      3 from catalyst.contrib.utils import *
----> 4 from catalyst.utils import *
      5 
      6 from .callbacks import filter_callbacks_by_node, sort_callbacks_by_order

~/.local/lib/python3.6/site-packages/catalyst/utils/__init__.py in <module>
     64 from .numpy import get_one_hot
     65 from .parser import parse_config_args, parse_args_uargs
---> 66 from .pipelines import clone_pipeline
     67 from .scripts import (
     68     import_module,

~/.local/lib/python3.6/site-packages/catalyst/utils/pipelines.py in <module>
      2 import shutil
      3 
----> 4 from git import Repo as repo  # noqa: N813
      5 
      6 from catalyst.utils.misc import copy_directory

~/.local/lib/python3.6/site-packages/git/__init__.py in <module>
      6 # flake8: noqa
      7 #@PydevCodeAnalysisIgnore
----> 8 from git.exc import *                       # @NoMove @IgnorePep8
      9 import inspect
     10 import os

~/.local/lib/python3.6/site-packages/git/exc.py in <module>
      8 from gitdb.exc import BadName  # NOQA @UnusedWildImport skipcq: PYL-W0401, PYL-W0614
      9 from gitdb.exc import *     # NOQA @UnusedWildImport skipcq: PYL-W0401, PYL-W0614
---> 10 from git.compat import safe_decode
     11 
     12 # typing ----------------------------------------------------

~/.local/lib/python3.6/site-packages/git/compat.py in <module>
     30     overload,
     31 )
---> 32 from git.types import TBD
     33 
     34 # ---------------------------------------------------------------------------

~/.local/lib/python3.6/site-packages/git/types.py in <module>
     10     from typing import Final, Literal, SupportsIndex  # noqa: F401
     11 else:
---> 12     from typing_extensions import Final, Literal, SupportsIndex  # noqa: F401
     13 
     14 

ImportError: cannot import name 'SupportsIndex'

How can I fix this problem?

**Comment by Nic-Ma** [comment]
Hi @Ouyuxuan623 ,

Thanks for your feedback, could you please help provide more info about what tutorial you are testing?
@yiheng-wang-nv , did you observe this issue when you test tutorial for v0.8.1?

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
> did you observe this issue when you test tutorial for v0.8.1?
Hi @Nic-Ma , I did not meet error when using monai v0.8.1 or using the latest commit(`d6327a765cf23dafd680b2a4b472edf9639e1087 `). The notebook I checked is `unet_segmentation_3d_catalyst.ipynb`, where `catalyst==20.07` is installed via running the first cell.
