### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'to_onehot_y'

### ISSUE THREAD

**Issue by Ordgod** [Project-MONAI/tutorials#60]
**Describe the bug**
The code from [A U-Net model for lung lesion segmentation from CT images](https://github.com/Project-MONAI/tutorials/tree/master/3d_segmentation/challenge_baseline/) could not be runned. 

The error information is: `TypeError: __init__() got an unexpected keyword argument 'to_onehot_y'`.

**To Reproduce**
1. Go to `https://github.com/Project-MONAI/tutorials/tree/master/3d_segmentation/challenge_baseline/`
2. Install MONAI by `pip install "git+https://github.com/Project-MONAI/MONAI#egg=monai[nibabel,ignite,tqdm]"`
3. Run commands `python run_net.py train --data_folder "COVID-19-20_v2/Train" --model_folder "runs"`

**Expected behavior**
Start training of the model.

**Screenshots**
![image](https://user-images.githubusercontent.com/34941987/98549459-199e1d80-229b-11eb-9053-9c76fbf9d7c1.png)

**Environment (please complete the following information):**
 - OS: CentOS
 - Python version: 3.6
 - MONAI version [e.g. git commit hash]: 0.3.0
 - CUDA/cuDNN version: 
 - GPU models and configuration

**Additional context**
https://covid-segmentation.grand-challenge.org/Resource/

**Comment by Nic-Ma** [comment]
Hi @Ordgod ,

This is a known issue, @yiheng-wang-nv is working on it to update all the tutorials and examples.
Please use the code under tag `0.3.0` instead of the master branch.

Thanks.

**Comment by wyli** [comment]
I'm currently working on a fix for the baseline. cc @yiheng-wang-nv @Nic-Ma (v0.3.0 won't work as we created a new network instance for it.)

**Comment by Nic-Ma** [comment]
> I'm currently working on a fix for the baseline. cc @yiheng-wang-nv @Nic-Ma (v0.3.0 won't work as we created a new network instance for it.)

OK, I see. This is the new added tutorial.
@yiheng-wang-nv is already working on a PR to update all the notebooks and examples, will finish it soon.

Thanks.
