### ISSUE TITLE
AttributeError: module 'monai.networks.nets' has no attribute 'BasicUNet'

### ISSUE THREAD

**Issue by Ordgod** [Project-MONAI/tutorials#61]
**Describe the bug**
The code from [A U-Net model for lung lesion segmentation from CT images](https://github.com/Project-MONAI/tutorials/tree/master/3d_segmentation/challenge_baseline/) could not be runned. 

The error information is: `TypeError: __init__() got an unexpected keyword argument 'to_onehot_y'`.

**To Reproduce**
1. Go to `https://github.com/Project-MONAI/tutorials/tree/master/3d_segmentation/challenge_baseline/`
2. Install MONAI by `pip install monai`. **NOTE: this is important. Different install methods lead to different  errors** #60 
3. Run commands `python run_net.py train --data_folder "COVID-19-20_v2/Train" --model_folder "runs"`

**Expected behavior**
Start training of the model.

**Screenshots**
![image](https://user-images.githubusercontent.com/34941987/98549592-4c481600-229b-11eb-8c4a-af814e5c1fec.png)

**Environment (please complete the following information):**
 - OS: CentOS
 - Python version: 3.6
 - MONAI version [e.g. git commit hash]: 0.3.0
 - CUDA/cuDNN version: 
 - GPU models and configuration

**Additional context**
https://covid-segmentation.grand-challenge.org/Resource/

**Comment by wyli** [comment]
thanks for reporting, that baseline script won't work with `pip install monai` at the moment, because we haven't included it in the milestone release.
