### ISSUE TITLE
broken illustrations in MONAIBootcamp2021 notebooks

### ISSUE THREAD

**Issue by hw-ju** [Project-MONAI/tutorials#613]
The nice illustrations within MONAIBootcamp2021 notebooks are broken. When I run them in Colab now, they're no longer there. Could you help fix them?
https://github.com/Project-MONAI/MONAIBootcamp2021

**Comment by hw-ju** [comment]
Thanks! @wyli 
All three `Day 1` notebooks https://github.com/Project-MONAI/MONAIBootcamp2021. 

Those Colab notebooks are great for new users to try out MONAI with more comments than other tutorials, and the illustrations/diagrams within are essential to explain e.g., how Ignite/MONAI uses handlers to handle events. Besides, I guess new users watching the Bootcamp recordings will want to use those Colab notebooks. So I really hope those notebooks can be maintained.

**Comment by wyli** [comment]
cc @zephyrie any idea how we support this?

**Comment by zephyrie** [comment]
I'll work on fixing it. It seems like it's trying to load local images, and they aren't available.
