### ISSUE TITLE
Dlprof tool deprecated 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#628]
**Is your feature request related to a problem? Please describe.**
Dlprof has been end-of-lifed, would be great to revise the tutorial to use pytorch native profiler or nsight directly

**Comment by yiheng-wang-nv** [comment]
I'm fine to take this task.

**Comment by yiheng-wang-nv** [comment]
Hi @drbeh , in https://github.com/Project-MONAI/tutorials/blob/master/performance_profiling/pathology/profiling_train_base_nvtx.md it says `specific NVTX tags we added to track certain behaviors`, but I cannot find any related code of nvtx directly in the [py file](https://github.com/Project-MONAI/tutorials/blob/master/performance_profiling/pathology/train_evaluate_nvtx.py), could you explain more about how to use `nsys` for the profiling? I wish to take your tutorial for reference to modify the radiology part and replace the `dlprof`. Thanks!

**Comment by drbeh** [comment]
Hi @yiheng-wang-nv, we have implemented `Range` decorator and context manager in MONAI, which adds nvtx tags (for defining ranges) to transforms and code blocks as you can see in the code. On the other hand, nsys adds tags to many GPU kernel by default and you can use flags to disable or enable it.
Please let me know if you have any other question. 

https://github.com/Project-MONAI/tutorials/blob/ac88fee291720f4c2b9fcdcd7df93574df79425e/performance_profiling/pathology/train_evaluate_nvtx.py#L218-L275

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv, we have implemented `Range` decorator and context manager in MONAI, which adds nvtx tags (for defining ranges) to transforms and code blocks as you can see in the code. On the other hand, nsys adds tags to many GPU kernel by default and you can use flags to disable or enable it. Please let me know if you have any other question.
> 
> https://github.com/Project-MONAI/tutorials/blob/ac88fee291720f4c2b9fcdcd7df93574df79425e/performance_profiling/pathology/train_evaluate_nvtx.py#L218-L275

Hi @drbeh , thanks very much for the explain.
