### ISSUE TITLE
Learning rate is zero for first epoch in transchex_openi_multilabel_classification notebook

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/tutorials#630]
**Describe the bug**

Please only create issues here relating to the functioning of the tutorials. For all other questions/problems/bugs, please refer to MONAI's [main repository](https://github.com/Project-MONAI/MONAI). For MONAI bugs (not just a problem in the notebook), please create an [issue](https://github.com/Project-MONAI/MONAI/issues). For questions, please use the [Discussions tab](https://github.com/Project-MONAI/MONAI/discussions).

**To Reproduce**
Run [tutorial](https://github.com/Project-MONAI/tutorials/blob/master/multimodal/openi_multilabel_classification_transchex/transchex_openi_multilabel_classification.ipynb) and print learning rate in first epoch.

**Expected behavior**
See MONAI [issue](https://github.com/Project-MONAI/MONAI/issues/3989).

**Environment (please complete the following information):**
 - OS ubuntu 20.04.04
 - Python version 3.8
 - MONAI version 0.8.1

**Comment by Can-Zhao** [comment]
This is true. I verified it. Learning rate is zero for first epoch when using `WarmupCosineSchedule`

**Comment by wyli** [comment]
https://github.com/Project-MONAI/tutorials/pull/932 revise the scheduler usage.
