### ISSUE TITLE
The "freeze_support()" line can be omitted

### ISSUE THREAD

**Issue by petrasvobodova** [Project-MONAI/tutorials#631]
Hi,

I am using code from notebook unetr_btcv_segmentation_3d.ipynb.

However, when I am trying to run it, I am getting following error which I can't solve.

For line:
for step, batch in enumerate(epoch_iterator):

I received:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.

 if __name__ == '__main__':
        freeze_support()
         ...

The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.

Do you have any idea how to solve this issue?

**Comment by ericspod** [comment]
Are you running under Windows? This appears to be an issue with Jupyter and multiprocessing. If you set the `num_workers` for your data loader to 1 it will then not use multiple processes to load. This will be slower but avoids Windows issues with multiprocessing.

**Comment by petrasvobodova** [comment]
Thank you very much! This solved my problem.
