### ISSUE TITLE
Enhance MONAI Bundle tutorial

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/tutorials#648]
Here I wish to provide some suggestions about MONAI Bundle tutorial: see [here](https://github.com/Project-MONAI/tutorials/blob/a810488d96b878f830473fb5b6498b035f010617/modules/bundles/get_started.ipynb) 

1. In the section of `Execute training with bundle script - run`, the cells cannot be run in the notebook directly, thus should we change them into markdown cells?
2. As for the override function, it is a very helpful feature, but we may need to add this part in the doc: https://docs.monai.io/en/latest/bundle_intro.html (it seems missing). In addition, the sign `\` confuses me since it is not existing in the doc-strings of `def run` in the source code.

**Comment by Nic-Ma** [comment]
Thanks for your feedback, I will try to enhance them ASAP.
