### ISSUE TITLE
Data annotation error (3D Multi-Organ Tutorial)

### ISSUE THREAD

**Issue by jmjoseph21** [Project-MONAI/tutorials#651]
The data does not appear to have the annotations outlined in the tutorial, can you guide us towards the correct datasets?

**Comment by Nic-Ma** [comment]
Hi @ahatamiz , I think this question is asking about the UNETR tutorial? Could you please help share some info?

Thanks in advance.

**Comment by ahatamiz** [comment]
Hi @jmjoseph21 , please register [here](https://www.synapse.org/#!Synapse:syn3193805/wiki/217753) to download data with annotations.

**Comment by jmjoseph21** [comment]
This is where I have already downloaded the data but the tutorial is not clear how this downloaded link corresponds to the dataset reported in the paper.
