### ISSUE TITLE
Why does UNETR choose the last validation's accuracy as final validation accuracy in the trainning?

### ISSUE THREAD

**Issue by aubest** [Project-MONAI/tutorials#658]
HI, When I was trying to train the UNETR, I found that the last validation's result was always selected as  final validation accuracy, But I am confused why not to take the average?
![156907848-94dfb3f6-370f-448a-a24a-d1b30391ccb3](https://user-images.githubusercontent.com/28101192/163312046-6bf07033-23da-4589-9ce1-6e877e1e2af6.png)

**Comment by Nic-Ma** [comment]
Hi @ahatamiz ,

Could you please help take a look at this question?

Thanks in advance.

**Comment by ahatamiz** [comment]
Hi @aubest 

The final validation is simply just the accuracy of last epoch, but we keep track of best validation accuracy and final validation accuracy by saving their corresponding checkpoints. Taking the average is also possible, but may not be very useful for saving a particular checkpoint.
