### ISSUE TITLE
MONAI flags: HAS_EXT = False, USE_COMPILED = False

### ISSUE THREAD

**Issue by Ordgod** [Project-MONAI/tutorials#66]
What does this line meaning?? 
I wanted to reproduce the [baseline lesion network](https://github.com/Project-MONAI/tutorials/tree/master/3d_segmentation/challenge_baseline)
Every time I started training, this line occured. Is there something wrong??

**Comment by wyli** [comment]
thanks for the question. that's expected, those flags are reserved for some future c++/cuda based features (https://github.com/Project-MONAI/MONAI/tree/master/monai/csrc) which are currently experimental.
