### ISSUE TITLE
review notebooks with reviewnb

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/Tutorials#7]
install reviewnb https://www.reviewnb.com/ on this repo for diff & Commenting pull requests of jupyter notebooks

**Comment by wyli** [comment]
could you please help with this ticket? @Nic-Ma @IsaacYangSLA

**Comment by Nic-Ma** [comment]
Add `ReviewNB`:
![image](https://user-images.githubusercontent.com/27533405/91273829-6308c180-e7b0-11ea-97f6-08e1e39b3ab7.png)

Thanks.

**Comment by wyli** [comment]
https://app.reviewnb.com/Project-MONAI/Tutorials/
