### ISSUE TITLE
WASSERTEIN distance

### ISSUE THREAD

**Issue by natacanta5** [Project-MONAI/tutorials#70]
Hello, I wanted to ask if anyone has used Wasserstein distance in brain different structures segmentation because I have some issues. For example, the argument that I should pass to my pipeline is a matrix distance and I would like to know how I construct this matrix, I don't know where those numbers come from. And the other question if is the loss of Wasserstein distance is finished and prove in any experiment (not in brain tumor because the labels are continuous and my labels are separated).

Thank you.

**Comment by wyli** [comment]
see https://github.com/Project-MONAI/MONAI/issues/1267
