### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#717]
In line with other other projects including MONAI Core, I feel we should rename our `master` branch as `main`. 

@wyli Although renaming the branch is easy, I'm worried about breaking cron jobs etc. What do you think?

**Comment by rijobro** [comment]
Using `egrep` all of our Colab links would have to be changed, e.g.: 

`
"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Project-MONAI/tutorials/blob/master/2d_classification/mednist_tutorial.ipynb)"`

to 

`
"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Project-MONAI/tutorials/blob/main/2d_classification/mednist_tutorial.ipynb)"
`

**Comment by wyli** [comment]
thanks for the reminder, I think we should do this, I'll rename it now, please help fix any issues as well... cc @Project-MONAI/core-reviewers

**Comment by wyli** [comment]
![Screenshot 2022-05-19 at 10 57 18](https://user-images.githubusercontent.com/831580/169266998-e5df937e-3e70-41d9-8e6d-9c4aa891d207.png)

**Comment by wyli** [comment]
> Using `egrep` all of our Colab links would have to be changed, e.g.:
> 
> ` "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Project-MONAI/tutorials/blob/master/2d_classification/mednist_tutorial.ipynb)"`
> 
> to
> 
> `"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Project-MONAI/tutorials/blob/main/2d_classification/mednist_tutorial.ipynb)"`

looks like the previous URL is redirected to the renamed one and it's not an issue in this case

**Comment by rijobro** [comment]
Great, we'll still need to update the cron jobs in the MONAI repository though, right?

I created a PR to rename the URLs, do you think we should merge or close that one?
