### ISSUE TITLE
Log and plotting result for training proccess

### ISSUE THREAD

**Issue by Leong1230** [Project-MONAI/tutorials#74]
Thank you for the tutorials!

I can't find any log files saved in ./run and it seems that this part is not included in the code.  (./3d_segmentation/baseline)
It would be much clearer if the training information is saved and plotted.

Anthor question is that, do the images under 'Validation' folder have labels (groung truth?) and where is it?

Thank you!

**Comment by wyli** [comment]
Hello! we'd like to keep that baseline minimal, so there's no plan to add more visualisation functionality.
for tensorboard eventhandlers please search through this repo, there are plenty of tutorials: https://github.com/Project-MONAI/tutorials/search?q=tensorboard

**Comment by wyli** [comment]
the 'validation' here is not to be confused with the challenge's validation data, it's a local 80/20 train/val split: https://github.com/Project-MONAI/tutorials/blob/db4bf838c07c628b3887ba1bb56fc5dd687a1c5b/3d_segmentation/challenge_baseline/run_net.py#L135-L138
