### ISSUE TITLE
replace `AsChannelFirstd` with `EnsureChannelFirstd`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#748]
**Is your feature request related to a problem? Please describe.**
`EnsureChannelFirstd` is mostly more robust than `AsChannelFirstd` when used with `LoadImaged`. This is a feature request of replacing the current `AsChannelFirstd` cases with `EnsureChannelFirstd`.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I think we should also replace all the `AddChanneld` with `EnsureChannelFirstd`?
@KumoLiu could you please help update this when you completed all the tutorials?

Thanks in advance.

**Comment by wyli** [comment]
Yes, ensure channel first is almost always more robust...

**Comment by Nic-Ma** [comment]
@wyli And should we also update the array level `AddChannel` and `AsChannelFirst`?
I think `MetaTensor` also support `EnsureChannelFirst` in the array level?

Thanks.

**Comment by wyli** [comment]
yes, also the LoadImage has this flag, perhaps try the flag in some of the tutorials..
