### ISSUE TITLE
ValueError while training the model for Brain Tumor Segmentation

### ISSUE THREAD

**Issue by sekh77** [Project-MONAI/tutorials#78]
Hi there -

I'm new to MONAI and doing some learning of the brain tumor segmentation code - referring to the file brats_segmentation_3d.ipynb under tutorials/3d_segmentation. I'm using this code AS-IS in my Jupyter Notebook. While training on the Medical Decathlon dataset, exactly after epoch 2 I see the following error:

_epoch 2 average loss: 0.8960
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-ba3fce20c0be> in <module>
     54                 # metric_sum += value.item() * not_nans
     55                 # compute mean dice for TC
---> 56                 value_tc, not_nans = dice_metric(y_pred=val_outputs[:, 0:1], y=val_labels[:, 0:1])
     57                 not_nans = not_nans.item()
     58                 metric_count_tc += not_nans

ValueError: not enough values to unpack (expected 2, got 1)_

Can you please suggest anything to rectify this problem?

Many thanks,
Sekhar H.

**Comment by Nic-Ma** [comment]
Hi @sekh77 ,

Thanks for your bug report, this is compatible issue with latest MONAI code, I will fix it tomorrow.
Please install `monai==0.3.0` as it's the stable version.

Thanks.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I am afraid maybe your previous mdification to `not_nans` also breaks other tutorials, could you please help double confirm all the tutorials and examples which used `DiceMetric`?

Thanks.

**Comment by sekh77** [comment]
Hi @Nic-Ma -

This is the config report, and I see that I'm already on 0.3.0.

MONAI version: 0.3.0+29.g56dd27a
Python version: 3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
OS version: Linux (5.4.0-1031-azure)
Numpy version: 1.18.1
Pytorch version: 1.6.0
MONAI flags: HAS_EXT = True, USE_COMPILED = False

Optional dependencies:
Pytorch Ignite version: 0.4.2
Nibabel version: 3.2.0
scikit-image version: 0.16.2
Pillow version: 7.2.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: 3.11.0
TorchVision version: 0.8.1
ITK version: 5.1.1
tqdm version: 4.51.0

Thanks,
Sekhar H.

**Comment by Nic-Ma** [comment]
Hi @sekh77 ,

This is not exact 0.3.0, please try to use `pip install monai==0.3.0`.
Thanks.

**Comment by sekh77** [comment]
Ok, sure! Thank you.

Sekhar H.

**Comment by sekh77** [comment]
Hi @Nic-Ma -

I reinstalled MONAI to 0.3.0. But I still see exactly the same error after epoch 2. Here's my new config report:

MONAI version: 0.3.0
Python version: 3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
OS version: Linux (5.4.0-1031-azure)
Numpy version: 1.18.1
Pytorch version: 1.6.0
MONAI flags: HAS_EXT = False, USE_COMPILED = False

Optional dependencies:
Pytorch Ignite version: 0.4.2
Nibabel version: 3.2.0
scikit-image version: 0.16.2
Pillow version: 7.2.0
Tensorboard version: NOT INSTALLED or UNKNOWN VERSION.
gdown version: 3.11.0
TorchVision version: 0.8.1
ITK version: 5.1.1
tqdm version: 4.51.0

Thanks,
Sekhar H.

**Comment by sekh77** [comment]
Here's the error after reinstalling to 0.3.0:

epoch 2 average loss: 0.9216
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-9a667257090b> in <module>
     49                 val_outputs = post_trans(val_outputs)
     50                 # compute overall mean dice
---> 51                 value, not_nans = dice_metric(y_pred=val_outputs, y=val_labels)
     52                 not_nans = not_nans.item()
     53                 metric_count += not_nans

ValueError: not enough values to unpack (expected 2, got 1)


Thanks,
Sekhar H.

**Comment by Nic-Ma** [comment]
Hi @sekh77 ,

Sorry I didn't make it clear, you should also update this tutorial repo to use tag 0.3.0.

Thanks.

**Comment by sekh77** [comment]
How do I do that? I downloaded the file - brats_segmentation_3d.ipynb - locally into my VM, and running it using my Jupyter Notebook.

Thanks,
Sekhar H.

**Comment by Meddebma** [comment]
Hi, 

I'm using google colab and I tried to make the same training and evaluation with my own spleen dataset, but I've got the same problem after the 2nd epoch.
I reinstalled monai with the Version 0.3.0 but I still get this error after the 2nd epoch:
"ValueError: not enough values to unpack (expected 2, got 1)"
Is it already debugged or what should I wait? 

Thanks
Aymen

**Comment by sekh77** [comment]
Hi @Nic-Ma - 

Is this issue already fixed? Can I use the latest version?

Thanks,
Sekhar H.

**Comment by Nic-Ma** [comment]
Hi @sekh77 ,

Yes, I think so, you can use either the latest MONAI and latest tutorial, or MONAI 0.3 and tutorial 0.3.

Thanks.

**Comment by Meddebma** [comment]
Hi @sekh77,

did it work for you? I still have the same problem after installing MONAI 0.3 :/

Thanks,
Aymen

**Comment by yiheng-wang-nv** [comment]
> Hi @sekh77,
> 
> did it work for you? I still have the same problem after installing MONAI 0.3 :/
> 
> Thanks,
> Aymen

Hi, which tutorial version you used under MONAI 0.3? Could you please attach the error here? The MONAI version as well as the tutorial version should be consistent.

**Comment by Meddebma** [comment]
Hi @yiheng-wang-nv 

here is the link:
https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb

thanks!

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv
> 
> here is the link:
> https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb
> 
> thanks!

I see, the code is the updated version that the dice metric will return two values. Please install the latest MONAI and run your notebook.

**Comment by Meddebma** [comment]
> > Hi @yiheng-wang-nv
> > here is the link:
> > https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb
> > thanks!
> 
> I see, the code is the updated version that the dice metric will return two values. Please install the latest MONAI and run your notebook.

I did it in the beginning of code with:  %pip install monai==0.3.0
should l do it differently?

Thanks @yiheng-wang-nv

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv
> 
> here is the link:
> https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb
> 
> thanks!

Please use the commented line instead:
`pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI`

**Comment by Meddebma** [comment]
> > Hi @yiheng-wang-nv
> > here is the link:
> > https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb
> > thanks!
> 
> Please use the commented line instead:
> `pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI`

I just did it, I still have the same issue :/

https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb

**Comment by yiheng-wang-nv** [comment]
> > > Hi @yiheng-wang-nv
> > > here is the link:
> > > https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb
> > > thanks!
> > 
> > 
> > Please use the commented line instead:
> > `pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI`
> 
> I just did it, I still have the same issue :/
> 
> https://github.com/Meddebma/pyradiomics/blob/master/Spleen_dict.ipynb

According to the log in your link:
`Requirement already satisfied: MONAI from git+https://github.com/Project-MONAI/MONAI#egg=MONAI in /usr/local/lib/python3.6/dist-packages (0.3.0)`
Since your device already has MONAI 0.3.0, the latest version would not be installed.
Could you please uninstall MONAI 0.3.0 first, and then install the latest one?

**Comment by Meddebma** [comment]
Hi @yiheng-wang-nv 
It worked very well thank you :) 
Only the plotting of the GIF did not work, should I change something to see the visual output?
Thanks!

**Comment by pfdamasceno** [comment]
Hi, this seems to still be an issue for MONAI>=monai-0.6.0. Is that correct?

**Comment by Nic-Ma** [comment]
Hi @pfdamasceno ,

@yiheng-wang-nv is updating all the examples and tutorials for 0.6 release: https://github.com/Project-MONAI/tutorials/pull/246.

Thanks.
