### ISSUE TITLE
Detection bug

### ISSUE THREAD

**Issue by mjq93** [Project-MONAI/tutorials#783]
**Describe the bug**
when training detection module, bug occurs:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument min in method wrapper_clamp__Tensor)

The reason is that the output variable of the "use_inferer" mode and the  "not use_inferer" mode are of different types, one is CPU and the other GPU.

https://github.com/Project-MONAI/MONAI/blob/3b12a2403286b8681d9a98ea97c5a47c0ec9c742/monai/apps/detection/networks/retinanet_detector.py#L484

**Comment by wyli** [comment]
thanks for reporting, a patch has been merged to the dev version see https://github.com/Project-MONAI/MONAI/issues/4608
