### ISSUE TITLE
Dice Problem

### ISSUE THREAD

**Issue by BelieferQAQ** [Project-MONAI/tutorials#808]
from monai. metrics import DiceMetric
Hello, I use Dicemetric function to calculate dice index, but I use ribfrac data set (this is a rib fracture data set, the whole data set has five fracture types, and each CT contains only 1-3 of them),
Excuse me, the dice calculated by Dicemetric in training this data set should not be accurate?
Dicemetric calculates dice of all prospects separately, averages them separately, and adds them as dice indicators, right?

**Comment by KumoLiu** [comment]
Hi @BelieferQAQ,
DiceMetric can support both multi-classes and multi-labels tasks, I think in your task it can works well.
You may find more details in docstring of `DiceMetric` from  https://github.com/Project-MONAI/MONAI/blob/dev/monai/metrics/meandice.py

**Comment by BelieferQAQ** [comment]
Thank you for your answer! Hello, what is the general procedure for this function to calculate dice? I don't quite understand the calculation code. thank you

**Comment by KumoLiu** [comment]
Hi @BelieferQAQ,
For `DiceMetric`, it first calculate dice scores per batch and per class (shape [batch_size, num_classes]). Secondly it mean by channel , then by batch. Thanks.

**Comment by wyli** [comment]
https://github.com/Project-MONAI/tutorials/blob/main/modules/dice_loss_metric_notes.ipynb there's a tutorial on this topic

**Comment by BelieferQAQ** [comment]
> https://github.com/Project-MONAI/tutorials/blob/main/modules/dice_loss_metric_notes.ipynb ther


> Hi @BelieferQAQ, For `DiceMetric`, it first calculate dice scores per batch and per class (shape [batch_size, num_classes]). Secondly it mean by channel , then by batch. Thanks.

thank you very much

**Comment by BelieferQAQ** [comment]
> https://github.com/Project-MONAI/tutorials/blob/main/modules/dice_loss_metric_notes.ipynb there's a tutorial on this topic

thank you very much
