### ISSUE TITLE
Add Tensorboard 3D example in the visualization tutorial

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/tutorials#809]
**Is your feature request related to a problem? Please describe.**
As TensorBoard supports 3D visualization now, and @aylward already provided a nice tutorial:
https://www.kitware.com/tensorboardplugin3d-visualizing-3d-deep-learning-models-in-tensorboard/

We can enhance the MONAI visualization tutorial to include this new feature:
https://github.com/Project-MONAI/tutorials/blob/main/modules/transform_visualization.ipynb

**Comment by aylward** [comment]
@bnmajor
