### ISSUE TITLE
Deepedit workflow with Pretrained model

### ISSUE THREAD

**Issue by artony35** [Project-MONAI/tutorials#821]
For the deepedit workflow, is it possible to use a pretrained unetr/dynunet model to train a deepedit model instead of training everything from scratch?  Thank you!

**Comment by Nic-Ma** [comment]
Hi @SachidanandAlle ,

Could you please help take a look at this ticket?

Thanks.

**Comment by SachidanandAlle** [comment]
You can use pre trained models.. some of them trained over few public Dataset can be found at:
https://github.com/Project-MONAI/MONAILabel/releases/tag/data

Or in monai zoo.. https://github.com/Project-MONAI/model-zoo/tree/dev/models/spleen_deepedit_annotation
