### ISSUE TITLE
Using different image resolutions for training and testing

### ISSUE THREAD

**Issue by musk007** [Project-MONAI/tutorials#829]
**Please use MONAI's Discussions tab**
For questions relating to MONAI usage, please do not create an issue.

Instead, use [MONAI's GitHub Discussions tab](https://github.com/Project-MONAI/MONAI/discussions). This can be found on the MONAI repository's main page (not the tutorials) next to Issues and Pull Requests along the top.
![image_sizes](https://user-images.githubusercontent.com/62494162/180958844-af2281cf-dabe-437d-836e-7b3c9963de5f.png)
In most of the segmentation codes in the tutorials the resolution of crops used in training is smaller than that used for testing. I wanted to ask whether the reason behind that is similar to what's mentioned in the following image, cropped from paper : https://arxiv.org/abs/1906.06423, or if there was a different reason behind it.
Thank you for your time

**Comment by dongyang0122** [comment]
hi @musk007, using larger patch size for model inference is based on the evidences of performance improvement for several segmentation models. U-Net is a typical example. Increasing inference patch size for U-Net not only improve the model accuracy (by 1~2% in terms of Dice score), but also improves the model inference efficiency. For models other than U-Net, it would be better to run few ablation studies to investigate if increasing inference patch size is a good choice.

**Comment by musk007** [comment]
Thank you both for your help.
@dongyang0122 , @Nic-Ma
