### ISSUE TITLE
TensorRT tutorial

### ISSUE THREAD

**Issue by JunMa11** [Project-MONAI/tutorials#848]
Dear MONAI Team,

Thanks for the great tutorial on acceleration the training process.

https://github.com/Project-MONAI/tutorials/blob/main/acceleration/README.md

Would it be possible to provide some tutorials on using TensorRT to speed up the inference process (e.g., 3D segmentation)?

**Comment by Nic-Ma** [comment]
Hi @JunMa11 ,

I think `PyTorch TensorRT` lib can optimize a TorchScript model, and still use it as a regular TorchScript model in a PyTorch program, you can find more details: https://github.com/pytorch/TensorRT

Thanks.

**Comment by JunMa11** [comment]
Thanks:)
