### ISSUE TITLE
TensorboardImageHandler for challenge_baseline

### ISSUE THREAD

**Issue by massimilianoporzio** [Project-MONAI/tutorials#87]
Please can anybody tell me how to use the TensorboardimageHandler for the challnege_baseline script?
What is the output_transform to use?

**Comment by Nic-Ma** [comment]
Hi @massimilianoporzio ,

Thanks for your interest in MONAI tutorials.
You can refer to this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/ignite/unet_training_dict.py#L225

Thanks.

**Comment by massimilianoporzio** [comment]
What is output[0] in the example? What the engine of monai outputs? Inviato dal mio telefono Huawei-------- Messaggio originale --------Da: Nic Ma <notifications@github.com>Data: lun 14 dic 2020, 12:17A: Project-MONAI/tutorials <tutorials@noreply.github.com>Cc: MASSIMILIANO PORZIO <massimiliano.porzio@gmail.com>, Mention <mention@noreply.github.com>Oggetto: Re: [Project-MONAI/tutorials] TensorboardImageHandler for challenge_baseline (#87)
Hi @massimilianoporzio ,
Thanks for your interest in MONAI tutorials.
You can refer to this example:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/ignite/unet_training_dict.py#L225
Thanks.

**Comment by Nic-Ma** [comment]
Hi @massimilianoporzio ,

`output` is from this line:
https://github.com/Project-MONAI/tutorials/blob/master/3d_segmentation/ignite/unet_training_dict.py#L192
It's a standard ignite API.

Thanks.
