### ISSUE TITLE
Breast Density Challenge training gets stuck occasionally - server keeps getting task requests from one of the sites and responding with __try_again__ tasks in a loop

### ISSUE THREAD

**Issue by siomvas** [Project-MONAI/tutorials#870]
@holgerroth 

Issue: 
Training occasionally stalls, the server keeps getting task requests from one of the sites and responding with `__try_again__` tasks in a loop.
**Steps to replicate**
I encountered this with multiple configs, issue seems to appear when initiating a new run from the same terminal that a run was already completed/run on. It appears the server silently crashes and the only output is the client task requests.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/60899041/185301387-b0475be7-77c5-4ae2-8a04-3a6a5cc897d5.png">

**Environment**
 - Windows 11 + WSL
 - Python 3.8

**Comment by holgerroth** [comment]
Hi @siomvas, thanks for raising this issue. Could you please attach your server and client logs? You might have to docker exec into each container and copy them out from `/code/fl_workspace`.

**Comment by siomvas** [comment]
Sure, just had another stalled run.


[site-1.txt](https://github.com/Project-MONAI/tutorials/files/9375849/site-1.txt)
[site-2.txt](https://github.com/Project-MONAI/tutorials/files/9375850/site-2.txt)
[site-3.txt](https://github.com/Project-MONAI/tutorials/files/9375851/site-3.txt)
[server.txt](https://github.com/Project-MONAI/tutorials/files/9375852/server.txt)

**Comment by holgerroth** [comment]
Thanks for sharing. Your site-1 already completed the training for this round (Round 1). However, site-2 and site-3 are stuck in the training epoch.
```
2022-08-18 16:29:42,461 - MammoLearner - INFO - [run=2, peer=fl_project, peer_run=2, task_name=train, task_id=c61f2dba-ec65-472a-8755-11da87de8f3c]: Local epoch site-2: 1/10 (lr=0.001)
2022-08-18 16:29:55,907 - MammoLearner - INFO - [run=2, peer=fl_project, peer_run=2, task_name=train, task_id=bb5a05cc-a679-45dd-b773-524f192ba70e]: Local epoch site-3: 4/10 (lr=0.001)
```
Hence, the server is not continuing to the next round and you are seeing the `asked client to try again later` message send to site-1.

I'm not sure though why your site-2 and 3 training got stuck... Maybe a resource issue? Are you running out of memory?

**Comment by siomvas** [comment]
Update:

The problem is indeed the silent failure of one (or two) of the sites.

Running out of CUDA memory as you pointed out is one of the sources of this, however I fixed that by lowering the batch size to 16 with the default model to get it to use less than the 12GB of my 3080Ti.

The bug remains, however:

I should point out the bug is intermittent, a run might finish successfully and then if I try to re-run it one site hangs as above. At first I thought it might be platform specific due to WSL virtualization and so on, so I switched from W11+WSL to Ubuntu with no luck.

I think I've narrowed it down to the following error

```
OMP: Error #15: Initializing libomp.so, but found unknown library already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
```



The common fix I found online for it is adding

`os.environ['KMP_DUPLICATE_LIB_OK']='True'`


I add that to the mammo learner, but that leads to Pytorch errors related to multi-processing such as

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_657_3> in read-write mode
```

```
Original Traceback (most recent call last):
  File "/opt/monai/monai/data/utils.py", line 276, in list_data_collate
    ret[k] = default_collate([d[k] for d in data])
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 54, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/opt/conda/lib/python3.8/site-packages/torch/storage.py", line 157, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_584_1> in read-write mode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/opt/monai/monai/data/utils.py", line 289, in list_data_collate
    raise RuntimeError(re_str) from re
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_584_1> in read-write mode
```

**Comment by holgerroth** [comment]
@siomvas, did you manage to get it to work?

**Comment by siomvas** [comment]
Did not manage to fix this, but further successful testing on different hardware with more GPU memory suggests this is an issue caused by lack of GPU memory, regardless of `nvidia-smi` not showing full memory utilisation at the time of crash/stall. Perhaps error logging can be propagated differently through Flare, as currently the fails are silent, but that is unrelated to the challenge. Closing this as a Challenge issue.

**Comment by holgerroth** [comment]
Thank you, @siomvas . Please feel free to raise an issue in https://github.com/NVIDIA/NVFlare/issues
