### ISSUE TITLE
Model fine tuning (Pytorch Lightning)

### ISSUE THREAD

**Issue by Meddebma** [Project-MONAI/tutorials#89]
I trained the spleen segmentation model for 200 epochs with the decathlon database. Then I evaluated it with my own dataset and the segmentation performance was extremely poor, do you know how I can finetune the model parameters with my own dataset? how should I do that and how many epochs should I do? (My dataset comprehend 20 manually segmented spleens)

Thanks
Aymen

**Comment by wyli** [comment]
hi @Meddebma there's a finetuning tutorial https://github.com/Project-MONAI/tutorials/blob/master/modules/layer_wise_learning_rate.ipynb using this monai function to assign different learning rates to different layers https://docs.monai.io/en/latest/optimizers.html?highlight=generate_param_groups#monai.optimizers.generate_param_groups
