### ISSUE TITLE
BTCV performance

### ISSUE THREAD

**Issue by jamesben6688** [Project-MONAI/tutorials#894]
Hi Ali. In the tutorial of BTCV multi-organ [segmentation,](https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/unetr_btcv_segmentation_3d.ipynb) the val dice score is about 80%. How can I get it to 88%, like in the unetr paper. Just more iterations? May I know how many iterations is needed? Thank you.

**Comment by tangy5** [comment]
HI @jamesben6688 , thanks for using the tutorial and UNETR. The tutorial is for quick implementation and quickstart. The performance is the paper is trained with multiple-GPU, larger batch size, more iterations and addition data. Hyperparameters are tunned to reach optimal performance. If computing resources allows, you could try larger batch size, DDP training, etc ... for further improving performance. Thank you!
