### ISSUE TITLE
Using synthetic data in the deepatlas tutorial notebook?

### ISSUE THREAD

**Issue by magicknight** [Project-MONAI/tutorials#898]
Hello,

Thank you for the nice tutorial!
I am trying to run the deepatlas tutorial with synthetic data. 
However, since monai.data.synthetic.create_test_image_3d generates objects with random position, 
The registration of each pair of these data makes no sense to me.  What do you think?

**Comment by wyli** [comment]
I think this synthetic example is about a single noisy circle/sphere being randomly scaled/translated

**Comment by magicknight** [comment]
> I think this synthetic example is about a single noisy circle/sphere being randomly scaled/translated

Thanks, so I think registration between them makes no sense? Since the position and size are randomly selected? It is not like the parts in organs.
