### ISSUE TITLE
Cross fold validation

### ISSUE THREAD

**Issue by Jamshidhsp** [Project-MONAI/tutorials#902]
Hi, 
Thanks for your great project. Is there any option available for k-fold validation during the training?

**Comment by wyli** [comment]
yes, please see https://github.com/Project-MONAI/tutorials/blob/main/modules/cross_validation_models_ensemble.ipynb

**Comment by Jamshidhsp** [comment]
Thank you for your answer. It is very useful. But I was wondering if this method is implemented in BTCV, UNETR code development?
