### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'orig_data_list_file_path' when run luna16_prepare_images.py

### ISSUE THREAD

**Issue by halftheworldaway** [Project-MONAI/tutorials#906]
## 1. Thank you for the good tutorials! 😊
I'm having some problems trying to do experiments on the luna16 dataset. In section 3.1 prepare your data part,  I run luna16_prepare_env_files.py as instructed and successfully generated the json file, but when I try to run luna16_prepare_images.py, i get an error as the title says. And i also didn't find "orig_data_list_file_path" in luna16_prepare_env_files.py.

So I'm a little confused about 'orig_data_list_file_path' now, am I missing some steps?

### 2.1 Config file
![image](https://user-images.githubusercontent.com/50624245/189256478-06d8ddb8-bdd8-45c0-87f7-23d26c76bfde.png)

### 2.2 Error message
![image](https://user-images.githubusercontent.com/50624245/189256553-07a6b174-e611-4423-b757-fd0514192d5a.png)

**Comment by KumoLiu** [comment]
Hi @Can-Zhao, can you help to take a look at this issue and share some information？
Thanks in advance!

**Comment by halftheworldaway** [comment]
@Can-Zhao I still haven't figured out how to solve this problem, looking forward to your reply.

**Comment by Can-Zhao** [comment]
Hi @halftheworldaway , please change `orig_data_list_file_path` to `data_list_file_path`. I will submit a PR to fix it. Thank you so much for catching it!
