### ISSUE TITLE
verify notebooks using the latest monai 0.4.0 pypi release

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#91]
subtask of https://github.com/Project-MONAI/MONAI/issues/1318
need to 
- check that `pip install monai[all]` works for all the notebooks and demos
- tag a 0.4.0 version of this repo

**Comment by wyli** [comment]
could you help look into this? @Nic-Ma

**Comment by Nic-Ma** [comment]
Sure, I am working on a PR for it.

Thanks.

**Comment by wyli** [comment]
thanks @Nic-Ma  I'll double check the colabs
