### ISSUE TITLE
MeanDice TypeError: __init__() got an unexpected keyword argument 'reduction'

### ISSUE THREAD

**Issue by Muhammad-Raza156** [Project-MONAI/tutorials#915]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/38157696/189338432-1c7569d7-c9e3-45cd-9f82-7cb90f8b32c9.png">
unable to understand this error according to documentation this should be ok

**Comment by wyli** [comment]
could you please include the version and system environment info ?

**Comment by Muhammad-Raza156** [comment]
Problem is already resolved Monai version was creating an issue anyways
thanks for the response

**Comment by wyli** [comment]
thanks for confirming!
