### ISSUE TITLE
Update Triton Deployment MedNIST Tutorial

### ISSUE THREAD

**Issue by slbryson** [Project-MONAI/tutorials#925]
**Is your feature request related to a problem? Please describe.**
Support MONAI 1.0.0
**Describe the solution you'd like**
Modify requirements for tutorial to depend on MONAI 1.0.0

**Describe alternatives you've considered**

**Additional context**

**Comment by wyli** [comment]
fixed by https://github.com/Project-MONAI/tutorials/pull/926
