### ISSUE TITLE
Sliding Window Inference giving error on 0.4.0

### ISSUE THREAD

**Issue by architraj29** [Project-MONAI/tutorials#93]
Command used for Sliding Window Inference (on Monai 0.4.0 but its working fine on 0.3.0)

### Code Snippet:
---------------------------------------------------------------------------

```
for val_data in self.val_loader:
    val_step_start_time = time.time()
    val_images, val_labels = val_data["image"].to(self.device), val_data["label"].to(self.device)
    roi_size = (128, 128, 128)
    sw_batch_size = 6
    if amp:
        with torch.cuda.amp.autocast():
            val_outputs = sliding_window_inference(val_images, roi_size, sw_batch_size, self.network, sw_device=self.device, device=self.device)
    else:
    val_outputs = sliding_window_inference(val_images, roi_size, sw_batch_size, self.network)  
```
Getting same error with and without amp

### Error: 
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)
/data/archit/Liver/Experiments/monai/main.py in <module>
     25
     26 if __name__ == "__main__":
---> 27     main()

/data/archit/Liver/Experiments/monai/main.py in main()
     19         if args.continue_training == True:
     20             trainer.load_best_checkpoint()
---> 21         trainer.trainProcess(amp=True)
     22
     23

/data/archit/Liver/Experiments/monai/TeraReconAI/train/segmentationTrainer.py in trainProcess(self, amp)
     71         self.initialize_network()
     72         amp_start = time.time()
---> 73         super()._trainProcess(amp)
     74         amp_total_time = time.time() - amp_start
     75         print(f"Total training time with AMP: {amp_total_time:.4f}")

/data/archit/Liver/Experiments/monai/TeraReconAI/train/trainer.py in _trainProcess(self, amp)
    168                         # else:
    169                         self.network = self.network.to(self.device)
--> 170                         val_outputs = sliding_window_inference(val_images, roi_size, sw_batch_size, self.network, sw_device=self.device, device=self.device)
    171
    172

/data/archit/Software/anaconda3/envs/monai/lib/python3.8/site-packages/monai/inferers/utils.py in sliding_window_inference(inputs, roi_size, sw_batch_size, predictor, overlap, mode, sigma_scale, padding_mode, cval, sw_device, device, *args, **kwargs)
    127         ]
    128         window_data = torch.cat([inputs[win_slice] for win_slice in unravel_slice]).to(sw_device)
--> 129         seg_prob = predictor(window_data, *args, **kwargs).to(device)  # batched patch segmentation
    130
    131         if not _initialized:  # init. buffer at the first iteration

AttributeError: 'list' object has no attribute 'to'

**Comment by Sichtermann** [comment]
Do you have a solution for this? Facing the same problem.

**Comment by Nic-Ma** [comment]
Hi @Sichtermann and @architraj29 ,

May I know what's your network? if `DynUNet`, please update to use the master branch of MONAI code.

Thanks.

**Comment by Sichtermann** [comment]
Yes running the DynUNet tutorial on my own data.
After updating the master branch and the respective lines in the tutorial, and upgrading to PyTorch 1.7.1 everything runs smoothly.
Thanks!
