### ISSUE TITLE
covid challenge evaluation

### ISSUE THREAD

**Issue by gscahhh** [Project-MONAI/tutorials#97]
hello, I am the participant of the covid challenge. Now, the submit has been closed. I have a new prediction and I want to know its dice score to do my own research. Could you please open the evaluation website for me or share the evaluation method? It will be better if the organization can release the ground truth labels of test and validation dataset. Thank you so much!

**Comment by Nic-Ma** [comment]
Hi @ericspod and @wyli ,

Could you guys please help on this question？

Thanks in advance.

**Comment by wyli** [comment]
thanks @gscahhh, those are managed by the challenge organisers, please consult https://covid-segmentation.grand-challenge.org/Contact/
