### ISSUE TITLE
why I use dints algorithm just got dice 70 on Task04 dataset?

### ISSUE THREAD

**Issue by dirtycomputer** [Project-MONAI/tutorials#974]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by mingxin-zheng** [comment]
Hi @dirtycomputer , can you share a bit more info? I got about 0.88-0.90 on Task04 in my previous experiments.

**Comment by dongyang0122** [comment]
hi @dirtycomputer, can you share the details that how you applied the DiNTS algorithms? thanks!
