### ISSUE TITLE
autoencoder_mednist transformations failure

### ISSUE THREAD

**Issue by klimli** [Project-MONAI/tutorials#99]
**Describe the bug**

When running the current version of autoencoder_mednist tutorial it will crash while trying to perform transformations on data. Specifically while creating CasheDataset. 

**To Reproduce**
Simply run all the cells until you reach creating the CasheDataset - that's where it crashes

**Expected behavior**
It should perform the transformations

**Additional context**

Simple solution I found is to add "reader" parameter to LoadImageD transformation. In case of mednist Hand dataset(which is the default in this tutorial) it should be reader="PILReader" as all the images as .jpg

**Comment by rijobro** [comment]
Hi, it seems to be working for me. I'm using the master branch of MONAI, which required another bug fix (https://github.com/Project-MONAI/MONAI/pull/1440), but I didn't see any problems regarding the `CacheDataset`.

Would you be able to paste the error? And also the output of `monai.config.print_debug_info()`?

**Comment by klimli** [comment]
Hi, thank you for the fast response!

This the error output: 

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/monai/transforms/utils.py in apply_transform(transform, data, map_items)
    360             return [transform(item) for item in data]
--> 361         return transform(data)
    362     except Exception as e:

9 frames
RuntimeError: can not find suitable reader for this file: /tmp/tmpy56jd7rb/MedNIST/Hand/001061.jpeg.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/monai/transforms/utils.py in apply_transform(transform, data, map_items)
    361         return transform(data)
    362     except Exception as e:
--> 363         raise RuntimeError(f"applying transform {transform}") from e
    364 
    365 

RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f614b16d4a8>`

I'm running it on colab. Here is the debug info:

`================================
Printing MONAI config...
================================
MONAI version: 0.4.0
Numpy version: 1.19.5
Pytorch version: 1.7.0+cu101
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 0563a4467fa602feca92d91c7f47261868d171a1

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: 3.0.2
scikit-image version: 0.16.2
Pillow version: 7.0.0
Tensorboard version: 2.4.0
gdown version: 3.6.4
TorchVision version: 0.8.1+cu101
ITK version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.56.0
lmdb version: 0.99
psutil version: 5.4.8

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 18.04.5 LTS
Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Processor: x86_64
Machine: x86_64
Python version: 3.6.9
Process name: python3
Command: ['/usr/bin/python3', '-m', 'ipykernel_launcher', '-f', '/root/.local/share/jupyter/runtime/kernel-e3bb8ea8-c3d8-4786-82c8-12db0bdb7b51.json']
Open files: []
Num physical CPUs: 1
Num logical CPUs: 2
Num usable CPUs: 2
CPU usage (%): [7.2, 6.7]
CPU freq. (MHz): UNKNOWN for given OS
Load avg. in last 1, 5, 15 mins (%): UNKNOWN for given OS
Disk usage (%): 47.7
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 12.7
Available memory (GB): 11.8
Used memory (GB): 0.7

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 10.1
cuDNN enabled: True
cuDNN version: 7603
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75']
Info for GPU: 0
	Name: Tesla T4
	Is integrated: False
	Is multi GPU board: False
	Multi processor count: 40
	Total memory (GB): 14.7
	Cached memory (GB): 0.0
	Allocated memory (GB): 0.0
	CUDA capability (maj.min): 7.5`

**Comment by rijobro** [comment]
Hi, you're absolutely right. I think the problem relates to some changes caused by updates to how we read our images. 

In colab, I modified the first line to be: `%pip install -q "monai-weekly[pillow, tqdm]"`, and using the weekly release of MONAI solved that problem. You may need to restart the runtime after the pip install.

**Comment by rijobro** [comment]
Related update PR: https://github.com/Project-MONAI/MONAI/pull/1448.

**Comment by klimli** [comment]
Thank you. This solves the issue!
