### ISSUE TITLE
auto3dseg_autorunner_ref_api error

### ISSUE THREAD

**Issue by y070504** [Project-MONAI/tutorials#993]
(base) root@LAPTOP-C900652C:/deeplearning/covid_CT#  cd /deeplearning/covid_CT ; /usr/bin/env /root/miniconda3/bin/python /root/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 40267 -- /deeplearning/covid_CT/data_analyze.py 
2022-10-16 19:58:22,197 - INFO - Expected md5 is None, skip md5 check for file Task09_Spleen.tar.
2022-10-16 19:58:22,198 - INFO - File exists: Task09_Spleen.tar, skipped downloading.
2022-10-16 19:58:22,198 - INFO - Non-empty folder exists in Task09_Spleen, skipped extracting.
/root/miniconda3/lib/python3.9/site-packages/monai/apps/auto3dseg/data_analyzer.py:131: UserWarning: File ./ref_api_work_dir/data_stats.yaml already exists and will be overwritten.
  warnings.warn(f"File {output_path} already exists and will be overwritten.")
100%|██████████████████████████████████████████████████████████████████████████████| 40/40 [01:46<00:00,  2.65s/it]
2022-10-16 20:00:08,390 - WARNING - Data is not completely uniform. MONAI transforms may provide unexpected result
algo_templates.tar.gz: 100%|████████████████████████████████████████████████████| 280k/280k [00:03<00:00, 82.2kB/s]
2022-10-16 20:00:12,022 - INFO - Downloaded: /tmp/tmplwyvwjz_/algo_templates.tar.gz
2022-10-16 20:00:12,022 - INFO - Expected md5 is None, skip md5 check for file /tmp/tmplwyvwjz_/algo_templates.tar.gz.
2022-10-16 20:00:12,022 - INFO - Writing into directory: ./ref_api_work_dir.
2022-10-16 20:00:12,512 - INFO - ./ref_api_work_dir/segresnet2d_0
2022-10-16 20:00:12,846 - INFO - ./ref_api_work_dir/segresnet2d_1
2022-10-16 20:00:13,239 - INFO - ./ref_api_work_dir/segresnet2d_2
2022-10-16 20:00:13,521 - INFO - ./ref_api_work_dir/segresnet2d_3
2022-10-16 20:00:13,908 - INFO - ./ref_api_work_dir/segresnet2d_4
2022-10-16 20:00:14,209 - INFO - ./ref_api_work_dir/dints_0
2022-10-16 20:00:14,500 - INFO - ./ref_api_work_dir/dints_1
2022-10-16 20:00:14,869 - INFO - ./ref_api_work_dir/dints_2
2022-10-16 20:00:15,154 - INFO - ./ref_api_work_dir/dints_3
2022-10-16 20:00:15,525 - INFO - ./ref_api_work_dir/dints_4
2022-10-16 20:00:15,816 - INFO - ./ref_api_work_dir/swinunetr_0
2022-10-16 20:00:16,193 - INFO - ./ref_api_work_dir/swinunetr_1
2022-10-16 20:00:16,506 - INFO - ./ref_api_work_dir/swinunetr_2
2022-10-16 20:00:16,871 - INFO - ./ref_api_work_dir/swinunetr_3
2022-10-16 20:00:17,241 - INFO - ./ref_api_work_dir/swinunetr_4
2022-10-16 20:00:17,555 - INFO - ./ref_api_work_dir/segresnet_0
2022-10-16 20:00:17,843 - INFO - ./ref_api_work_dir/segresnet_1
2022-10-16 20:00:18,224 - INFO - ./ref_api_work_dir/segresnet_2
2022-10-16 20:00:18,511 - INFO - ./ref_api_work_dir/segresnet_3
2022-10-16 20:00:18,899 - INFO - ./ref_api_work_dir/segresnet_4
{'num_iterations': 32, 'num_iterations_per_validation': 16, 'num_images_per_batch': 2, 'num_epochs': 2, 'num_warmup_iterations': 16}
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet_1 does not contain ref_api_work_dir/segresnet_1/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet_1
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/dints_1 does not contain ref_api_work_dir/dints_1/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/dints_1
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet_0 does not contain ref_api_work_dir/segresnet_0/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet_0
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/swinunetr_4 does not contain ref_api_work_dir/swinunetr_4/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/swinunetr_4
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/dints_2 does not contain ref_api_work_dir/dints_2/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/dints_2
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet2d_1 does not contain ref_api_work_dir/segresnet2d_1/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet2d_1
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/swinunetr_1 does not contain ref_api_work_dir/swinunetr_1/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/swinunetr_1
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/dints_4 does not contain ref_api_work_dir/dints_4/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/dints_4
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet2d_4 does not contain ref_api_work_dir/segresnet2d_4/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet2d_4
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet2d_2 does not contain ref_api_work_dir/segresnet2d_2/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet2d_2
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/dints_3 does not contain ref_api_work_dir/dints_3/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/dints_3
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet2d_3 does not contain ref_api_work_dir/segresnet2d_3/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet2d_3
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/swinunetr_2 does not contain ref_api_work_dir/swinunetr_2/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/swinunetr_2
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/dints_0 does not contain ref_api_work_dir/dints_0/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/dints_0
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet_3 does not contain ref_api_work_dir/segresnet_3/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet_3
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/swinunetr_0 does not contain ref_api_work_dir/swinunetr_0/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/swinunetr_0
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/swinunetr_3 does not contain ref_api_work_dir/swinunetr_3/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/swinunetr_3
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet_2 does not contain ref_api_work_dir/segresnet_2/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet_2
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet2d_0 does not contain ref_api_work_dir/segresnet2d_0/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet2d_0
  warnings.warn(
/root/miniconda3/lib/python3.9/site-packages/monai/auto3dseg/utils.py:340: UserWarning: ./ref_api_work_dir/segresnet_4 does not contain ref_api_work_dir/segresnet_4/algo_object.pkl.Now override the Algo output_path with: ref_api_work_dir/segresnet_4
  warnings.warn(
(base) root@LAPTOP-C900652C:/deeplearning/covid_CT#

**Comment by Nic-Ma** [comment]
Hi @mingxin-zheng ,

Could you please help take a look at the error message?

Thanks in advance.

**Comment by mingxin-zheng** [comment]
Thanks @Nic-Ma . Hi @y070504 , thanks for using the Auto3DSeg. Can you point out what error message you've seen in the notebook?  I only found lots of warning messages in the pasted contents.

Also, we recently have some fixes for out-of-memory issue. If you can provide the version of MONAI via the following bash commands, it will be helpful for us to solve the issue together:
```bash
python -c "import monai; print(monai.__version__)"
1.0.0+50.gda1c32ab
```

**Comment by y070504** [comment]
(base) root@LAPTOP-C900652C:/deeplearning/covid_CT# 
(base) root@LAPTOP-C900652C:/deeplearning/covid_CT# 
(base) root@LAPTOP-C900652C:/deeplearning/covid_CT# python -c "import monai; print(monai.__version__)"
1.0.0
(base) root@LAPTOP-C900652C:/deeplearning/covid_CT#
